import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedInterfaceShopping_Bag_01Widget1.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedAvatarWidget18.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedUserNameWidget2.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedPromocodesWidget1.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedUserNamegmailcomWidget2.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedArrowCaret_Right_SMWidget25.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedRectangle2Widget16.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedUserUser_CloseWidget1.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedArrowCaret_Right_SMWidget27.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedMyProfileWidget2.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedNotificationsWidget1.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedArrowCaret_Right_SMWidget26.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedInterfaceTicket_VoucherWidget1.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedVectorWidget811.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedArrowCaret_Right_SMWidget29.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedAvatarBackgroundWidget18.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedAboutUsWidget3.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedVector25Widget21.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedLogOutWidget1.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedFiuserWidget5.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedVectorWidget813.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedCommunicationBell_NotificationWidget1.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedRectangle7Widget7.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedMyOrdersWidget5.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedEditEdit_Pencil_01Widget5.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedArrowCaret_Right_SMWidget30.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedMyInformationsWidget2.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedArrowCaret_Right_SMWidget28.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedWarningInfoWidget1.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget1/generated/GeneratedUserID184B756Widget2.dart';

/* Frame Account
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAccountWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1284.8441619873047,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none, fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle2Widget16(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -51.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 347.0,
                              child: GeneratedRectangle7Widget7(),
                            ),
                            Positioned(
                              left: 311.0,
                              top: -107.0,
                              right: null,
                              bottom: null,
                              width: 239.564697265625,
                              height: 251.9700164794922,
                              child: GeneratedVectorWidget811(),
                            ),
                            Positioned(
                              left: 372.0,
                              top: 53.0,
                              right: null,
                              bottom: null,
                              width: 34.0,
                              height: 34.0,
                              child: GeneratedEditEdit_Pencil_01Widget5(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 70.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 0.0,
                              child: GeneratedVector25Widget21(),
                            ),
                            Positioned(
                              left: 145.0,
                              top: 57.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 27.0,
                              child: GeneratedMyProfileWidget2(),
                            ),
                            Positioned(
                              left: 145.0,
                              top: 151.0,
                              right: null,
                              bottom: null,
                              width: 144.0,
                              height: 25.0,
                              child: GeneratedUserNameWidget2(),
                            ),
                            Positioned(
                              left: 145.0,
                              top: 191.0,
                              right: null,
                              bottom: null,
                              width: 206.0,
                              height: 21.0,
                              child: GeneratedUserNamegmailcomWidget2(),
                            ),
                            Positioned(
                              left: 145.0,
                              top: 223.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 18.0,
                              child: GeneratedUserID184B756Widget2(),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 140.0,
                              right: null,
                              bottom: null,
                              width: 105.0,
                              height: 104.0,
                              child: GeneratedAvatarBackgroundWidget18(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 145.0,
                              right: null,
                              bottom: null,
                              width: 106.0,
                              height: 106.0,
                              child: GeneratedAvatarWidget18(),
                            ),
                            Positioned(
                              left: 134.546875,
                              top: 1032.8741455078125,
                              right: null,
                              bottom: null,
                              width: 239.564697265625,
                              height: 251.9700164794922,
                              child: GeneratedVectorWidget813(),
                            ),
                            Positioned(
                              left: 95.0,
                              top: 336.0,
                              right: null,
                              bottom: null,
                              width: 130.0,
                              height: 25.0,
                              child: GeneratedMyOrdersWidget5(),
                            ),
                            Positioned(
                              left: 95.0,
                              top: 411.0,
                              right: null,
                              bottom: null,
                              width: 211.0,
                              height: 25.0,
                              child: GeneratedMyInformationsWidget2(),
                            ),
                            Positioned(
                              left: 95.0,
                              top: 487.0,
                              right: null,
                              bottom: null,
                              width: 168.0,
                              height: 28.0,
                              child: GeneratedNotificationsWidget1(),
                            ),
                            Positioned(
                              left: 95.0,
                              top: 566.0,
                              right: null,
                              bottom: null,
                              width: 161.0,
                              height: 28.0,
                              child: GeneratedPromocodesWidget1(),
                            ),
                            Positioned(
                              left: 95.0,
                              top: 637.0,
                              right: null,
                              bottom: null,
                              width: 117.0,
                              height: 25.0,
                              child: GeneratedAboutUsWidget3(),
                            ),
                            Positioned(
                              left: 97.0,
                              top: 719.0,
                              right: null,
                              bottom: null,
                              width: 101.0,
                              height: 25.0,
                              child: GeneratedLogOutWidget1(),
                            ),
                            Positioned(
                              left: 367.0,
                              top: 330.0,
                              right: null,
                              bottom: null,
                              width: 38.0,
                              height: 38.0,
                              child: GeneratedArrowCaret_Right_SMWidget25(),
                            ),
                            Positioned(
                              left: 367.0,
                              top: 406.0,
                              right: null,
                              bottom: null,
                              width: 38.0,
                              height: 38.0,
                              child: GeneratedArrowCaret_Right_SMWidget26(),
                            ),
                            Positioned(
                              left: 367.0,
                              top: 482.0,
                              right: null,
                              bottom: null,
                              width: 38.0,
                              height: 38.0,
                              child: GeneratedArrowCaret_Right_SMWidget27(),
                            ),
                            Positioned(
                              left: 367.0,
                              top: 558.0,
                              right: null,
                              bottom: null,
                              width: 38.0,
                              height: 38.0,
                              child: GeneratedArrowCaret_Right_SMWidget28(),
                            ),
                            Positioned(
                              left: 367.0,
                              top: 634.0,
                              right: null,
                              bottom: null,
                              width: 38.0,
                              height: 38.0,
                              child: GeneratedArrowCaret_Right_SMWidget29(),
                            ),
                            Positioned(
                              left: 367.0,
                              top: 710.0,
                              right: null,
                              bottom: null,
                              width: 38.0,
                              height: 38.0,
                              child: GeneratedArrowCaret_Right_SMWidget30(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 482.0,
                              right: null,
                              bottom: null,
                              width: 38.0,
                              height: 38.0,
                              child:
                                  GeneratedCommunicationBell_NotificationWidget1(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 402.0,
                              right: null,
                              bottom: null,
                              width: 40.0,
                              height: 40.0,
                              child: GeneratedFiuserWidget5(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 328.0,
                              right: null,
                              bottom: null,
                              width: 41.0,
                              height: 41.0,
                              child: GeneratedInterfaceShopping_Bag_01Widget1(),
                            ),
                            Positioned(
                              left: 39.0,
                              top: 558.0,
                              right: null,
                              bottom: null,
                              width: 38.0,
                              height: 38.0,
                              child: GeneratedInterfaceTicket_VoucherWidget1(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 629.0,
                              right: null,
                              bottom: null,
                              width: 40.0,
                              height: 40.0,
                              child: GeneratedWarningInfoWidget1(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 707.0,
                              right: null,
                              bottom: null,
                              width: 44.0,
                              height: 44.0,
                              child: GeneratedUserUser_CloseWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
