import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedRectangle9Widget4.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedFoodonThewayWidget.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/Generated20June1030Widget.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedVectorWidget788.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/Generated30DtWidget.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedReOrderWidget.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedBaguetteBaguetteWidget8.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedRectangle18Widget3.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/Generated15minWidget.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedAjHrkqeGvr6NF3eZSs3f1Widget.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedRectangle8Widget10.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedRectangle22Widget5.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedTrackOrderWidget1.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedVectorWidget787.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedLastestOrderWidget.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedEllipse24Widget.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedRectangle17Widget5.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/Generated3itemsWidget1.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedNowWidget.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedRectangle19Widget4.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedHistoryWidget.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedRateWidget.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedOrderdeliveredWidget.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedRectangle15Widget.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedRectangle16Widget.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedMyOrdersWidget1.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedRectangle2Widget7.dart';
import 'package:untitled5/helpers/transform/transform.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedEstimatedTimeWidget.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedAjHrkqeGvr6NF3eZSs3f2Widget.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedVector25Widget12.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedUpcomingWidget.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedCancelWidget.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/Generated124479Widget.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedRectangle8Widget9.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedRectangle19Widget3.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/GeneratedBaguetteBaguetteWidget9.dart';
import 'package:untitled5/untitledapp/generatedorderswidget/generated/Generated3itemsWidget.dart';

import '../../theme/themee.dart';

/* Frame Orders
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOrdersWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 930,
              color: AppColors.six,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none, fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle2Widget7(),
                            ),
                            Positioned(
                              left: 311.0,
                              top: -107.0,
                              right: null,
                              bottom: null,
                              width: 239.564697265625,
                              height: 251.9700164794922,
                              child: GeneratedVectorWidget787(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 70.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 0.0,
                              child: GeneratedVector25Widget12(),
                            ),
                            Positioned(
                              left: 150.0,
                              top: 58.0,
                              right: null,
                              bottom: null,
                              width: 130.0,
                              height: 25.0,
                              child: GeneratedMyOrdersWidget1(),
                            ),
                            Positioned(
                              left: 134.546875,
                              top: 1050.8741455078125,
                              right: null,
                              bottom: null,
                              width: 239.564697265625,
                              height: 251.9700164794922,
                              child: GeneratedVectorWidget788(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 156.0,
                              right: null,
                              bottom: null,
                              width: 366.0,
                              height: 62.0,
                              child: GeneratedRectangle15Widget(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 161.0,
                              right: null,
                              bottom: null,
                              width: 176.0,
                              height: 53.0,
                              child: InkWell(onTap : (){} , child: GeneratedRectangle16Widget()),
                            ),
                            Positioned(
                              left: 58.0,
                              top: 176.0,
                              right: null,
                              bottom: null,
                              width: 138.0,
                              height: 28.0,
                              child: InkWell(onTap : (){} , child: GeneratedUpcomingWidget()),
                            ),
                            Positioned(
                              left: 261.0,
                              top: 176.0,
                              right: null,
                              bottom: null,
                              width: 99.0,
                              height: 28.0,
                              child: Container(width : 80 , height : 40 , child: InkWell(onTap : (){} , child: GeneratedHistoryWidget())),
                            ),
                            Column(
                              children: [
                                SizedBox(height: 250,),
                                Container(
                                  width: 350,
                                  height: 230,
                                  decoration: BoxDecoration(
                                    borderRadius: BorderRadius.circular(40),
                                    color: Colors.white,
                                  ),
                                  child:
                                  Column(
                                    children: [
                                      SizedBox(height: 20,),
                                      Row(
                                        children: [
                                          SizedBox(width: 10,),
                                          ClipRRect(
                                            borderRadius: BorderRadius.circular(15.0),
                                            child: Image.asset(
                                              "assets/images/730fb5eca818b765788f68b314c27079ca14d511.png",
                                              height: 70,
                                              width: 70,
                                              fit: BoxFit.fitWidth,
                                            ),
                                          ),
                                          SizedBox(width: 8,),
                                          Column(
                                            crossAxisAlignment: CrossAxisAlignment.start,
                                            children: [
                                              Row(children : [Text('3 items',
                                              style: TextStyle(
                                                fontSize: 12,
                                                fontWeight: FontWeight.w400,
                                                fontFamily: 'Montserrat',
                                                color: Colors.grey,
                                              ),),
                                              SizedBox(width: 120,),
                                                Text('#124479',style: TextStyle(
                                                  fontSize: 12,
                                                  fontWeight: FontWeight.w400,
                                                  fontFamily: 'Montserrat',
                                                  color: AppColors.fifth,
                                                ),)
                                              ]),
                                              SizedBox(height: 4,),
                                              Text('Baguette & Baguette',style: TextStyle(
                                                fontSize: 15,
                                                fontWeight: FontWeight.w700,
                                                fontFamily: 'Montserrat',
                                              ),),
                                            ],
                                          ),
                                        ],
                                      ),
                                      SizedBox(height: 10,),
                                      Row(children: [
                                        SizedBox(width: 20,),
                                            Text('Estimated Time',style: TextStyle(
                                              fontSize: 12,
                                              fontWeight: FontWeight.w700,
                                              fontFamily: 'Montserrat',
                                              color: Colors.grey,
                                            ),),
                                        SizedBox(width: 180,),
                                        Text('Now',style: TextStyle(
                                          fontSize: 13,
                                          fontWeight: FontWeight.w700,
                                          fontFamily: 'Montserrat',
                                          color: Colors.grey,
                                        ),),
                                      ],),
                                      SizedBox(height: 4,),
                                      Row(children: [
                                        SizedBox(width: 20,),
                                        Text('15',style: TextStyle(
                                          fontSize: 30,
                                          fontWeight: FontWeight.w700,
                                          fontFamily: 'Montserrat',
                                        ),
                                        ),
                                        Text('min',style: TextStyle(
                                          fontSize: 15,
                                          fontWeight: FontWeight.w700,
                                          fontFamily: 'Montserrat',
                                        ),),
                                        SizedBox(width: 130,),
                                        Text('Food On the Way',style: TextStyle(
                                          fontSize: 14,
                                          fontWeight: FontWeight.w600,
                                          fontFamily: 'Montserrat',
                                        ),),
                                      ],),
                                      Row(children: [
                                        SizedBox(width: 50,),
                                            Container(
                                              width : 110,
                                              child: RaisedButton(onPressed: (){},child: Text('Cancel',style: TextStyle(
                                                fontSize: 13,
                                                fontWeight: FontWeight.w500,
                                                fontFamily: 'Montserrat',
                                              ),),
                                                color: Colors.white,
                                                shape: RoundedRectangleBorder(
                                                    borderRadius: BorderRadius.circular(30)),
                                              ),
                                            ),
                                        SizedBox(width: 20,),
                                        Container(
                                          width: 110,
                                          child: RaisedButton(onPressed: (){},child: Text('Track Order',style: TextStyle(
                                            color: Colors.white,
                                            fontSize: 13,
                                            fontWeight: FontWeight.w500,
                                            fontFamily: 'Montserrat',
                                          ),),
                                            color: AppColors.fifth,
                                            shape: RoundedRectangleBorder(
                                                borderRadius: BorderRadius.circular(30)),),
                                        ),
                                      ],),
                                    ],
                                  ),
                                ),
                                SizedBox(height: 80,),
                                Container(
                                  width: 350,
                                  height: 230,
                                  decoration: BoxDecoration(
                                    borderRadius: BorderRadius.circular(40),
                                    color: Colors.white,
                                  ),
                                  child:
                                  Column(
                                    children: [
                                      SizedBox(height: 20,),
                                      Row(
                                        children: [
                                          SizedBox(width: 10,),
                                          ClipRRect(
                                            borderRadius: BorderRadius.circular(15.0),
                                            child: Image.asset(
                                              "assets/images/730fb5eca818b765788f68b314c27079ca14d511.png",
                                              height: 70,
                                              width: 70,
                                              fit: BoxFit.fitWidth,
                                            ),
                                          ),
                                          SizedBox(width: 8,),
                                          Column(
                                            crossAxisAlignment: CrossAxisAlignment.start,
                                            children: [
                                              Row(children : [Text('20, June, 10:30',
                                                style: TextStyle(
                                                  fontSize: 12,
                                                  fontWeight: FontWeight.w400,
                                                  fontFamily: 'Montserrat',
                                                  color: Colors.grey,
                                                ),),
                                                SizedBox(width: 30,),
                                                Text('3items',style: TextStyle(
                                                  fontSize: 12,
                                                  fontWeight: FontWeight.w400,
                                                  fontFamily: 'Montserrat',
                                                  color: Colors.grey,
                                                ),),
                                                SizedBox(width: 30,),
                                                Text('30DT',style: TextStyle(
                                                  fontSize: 14,
                                                  fontWeight: FontWeight.w400,
                                                  fontFamily: 'Montserrat',
                                                  color: AppColors.fifth,
                                                ),)
                                              ]),
                                              SizedBox(height: 4,),
                                              Text('Baguette & Baguette',style: TextStyle(
                                                fontSize: 15,
                                                fontWeight: FontWeight.w700,
                                                fontFamily: 'Montserrat',
                                              ),),
                                            ],
                                          ),
                                        ],
                                      ),
                                      SizedBox(height: 10,),
                                      Row(children: [
                                        SizedBox(width: 20,),
                                        Icon(Icons.circle,size: 20,color: Colors.lightGreen),
                                        SizedBox(width: 6,),
                                        Text('Order Delivered',style: TextStyle(
                                          fontSize: 12,
                                          fontWeight: FontWeight.w700,
                                          fontFamily: 'Montserrat',
                                          color: Colors.lightGreen,
                                        ),),
                                      ],),
                                      SizedBox(height: 30,),
                                      Row(children: [
                                        SizedBox(width: 50,),
                                        Container(
                                          width : 110,
                                          child: RaisedButton(onPressed: (){},child: Text('Rate',style: TextStyle(
                                            fontSize: 13,
                                            fontWeight: FontWeight.w500,
                                            fontFamily: 'Montserrat',
                                          ),),
                                            color: Colors.white,
                                            shape: RoundedRectangleBorder(
                                                borderRadius: BorderRadius.circular(30)),
                                          ),
                                        ),
                                        SizedBox(width: 20,),
                                        Container(
                                          width: 110,
                                          child: RaisedButton(onPressed: (){},child: Text('Re-Order',style: TextStyle(
                                            color: Colors.white,
                                            fontSize: 13,
                                            fontWeight: FontWeight.w500,
                                            fontFamily: 'Montserrat',
                                          ),),
                                            color: AppColors.fifth,
                                            shape: RoundedRectangleBorder(
                                                borderRadius: BorderRadius.circular(30)),),
                                        ),
                                      ],),
                                    ],
                                  ),
                                ),
                              ],
                            ),
                            Positioned(
                              left: 30.0,
                              top: 507.0,
                              right: null,
                              bottom: null,
                              width: 201.0,
                              height: 29.0,
                              child: GeneratedLastestOrderWidget(),
                            ),
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
