import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generatedcartemptywidget/generated/GeneratedRectangle1Widget26.dart';
import 'package:untitled5/untitledapp/generatedcartemptywidget/generated/GeneratedVectorWidget755.dart';
import 'package:untitled5/untitledapp/generatedcartemptywidget/generated/GeneratedInterfaceShopping_Cart_01Widget4.dart';
import 'package:untitled5/untitledapp/generatedcartemptywidget/generated/GeneratedAvatarBackgroundWidget7.dart';
import 'package:untitled5/untitledapp/generatedcartemptywidget/generated/GeneratedAvatarWidget7.dart';
import 'package:untitled5/untitledapp/generatedcartemptywidget/generated/GeneratedArrowCaret_Right_SMWidget14.dart';
import 'package:untitled5/untitledapp/generatedcartemptywidget/generated/GeneratedA28SecondFloorSector64Noida20130102Widget8.dart';
import 'package:untitled5/untitledapp/generatedcartemptywidget/generated/GeneratedDelivertoWidget4.dart';
import 'package:untitled5/untitledapp/generatedsendemailwidget/generated/GeneratedWavy_Tech28_Single10Converted1Widget.dart';

import '../../theme/themee.dart';

/* Frame Cart Empty
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCartWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
                return SingleChildScrollView(
                  scrollDirection: Axis.vertical,
                  child: Container(
                      height: 926.0,
                      color: AppColors.six,
                      child: Stack(children: [
                        Container(
                            width: constraints.maxWidth,
                            child: Container(
                              width: 428.0,
                              height: 926.0,
                              child: Stack(
                                  clipBehavior: Clip.none, fit: StackFit.expand,
                                  alignment: Alignment.center,
                                  children: [
                                    ClipRRect(
                                      borderRadius: BorderRadius.zero,
                                      child: Container(
                                        color: AppColors.six,
                                      ),
                                    ),
                                    Positioned(
                                      left: -1.0,
                                      top: 0.0,
                                      right: null,
                                      bottom: null,
                                      width: 429.0,
                                      height: 926.0,
                                      child: GeneratedRectangle1Widget26(),
                                    ),
                                    Positioned(
                                      left: 19.0,
                                      top: 40.0,
                                      right: null,
                                      bottom: null,
                                      width: 58.0,
                                      height: 58.0,
                                      child: GeneratedAvatarBackgroundWidget7(),
                                    ),
                                    Positioned(
                                      left: 19.0,
                                      top: 43.0,
                                      right: null,
                                      bottom: null,
                                      width: 59.0,
                                      height: 59.0,
                                      child: GeneratedAvatarWidget7(),
                                    ),
                                    Positioned(
                                      left: 172.0,
                                      top: 47.0,
                                      right: null,
                                      bottom: null,
                                      width: 87.0,
                                      height: 17.0,
                                      child: GeneratedDelivertoWidget4(),
                                    ),
                                    Positioned(
                                      left: 109.0,
                                      top: 66.0,
                                      right: null,
                                      bottom: null,
                                      width: 212.0,
                                      height: 30.0,
                                      child:
                                      GeneratedA28SecondFloorSector64Noida20130102Widget8(),
                                    ),
                                    Positioned(
                                      left: 278.9794921875,
                                      top: 41.0,
                                      right: null,
                                      bottom: null,
                                      width: 27.979501724243164,
                                      height: 27.979501724243164,
                                      child: GeneratedArrowCaret_Right_SMWidget14(),
                                    ),
                                    Positioned(
                                      left: 328.0,
                                      top: -116.0,
                                      right: null,
                                      bottom: null,
                                      width: 239.564697265625,
                                      height: 251.9700164794922,
                                      child: GeneratedVectorWidget755(),
                                    ),
                                    Positioned(
                                      left: 358.0,
                                      top: 50.0,
                                      right: null,
                                      bottom: null,
                                      width: 43.0,
                                      height: 43.0,
                                      child:
                                      InkWell(onTap : (){} ,child: GeneratedInterfaceShopping_Cart_01Widget4()),
                                    ),
                                    Column(
                                      children: [
                                        SizedBox(height: 190,),
                                        Row(
                                            children:[ Container(
                                              margin: EdgeInsets.only(right: 130),
                                              child: IconButton(
                                                icon: Icon(Icons.arrow_back,size: 30,color: Colors.grey,),
                                                onPressed: (){},
                                              ),
                                            ),
                                              Text('Cart',style: TextStyle(
                                                fontSize: 25,
                                                fontWeight: FontWeight.w500,
                                                fontFamily: 'Montserrat',
                                                color: Colors.grey.withOpacity(0.7),
                                              ),)
                                            ]
                                        ),
                                        SizedBox(height: 20,),

                                        Container(
                                          width: 380,
                                          height: 90,
                                          decoration: BoxDecoration(
                                            borderRadius: BorderRadius.circular(30),
                                            color: Colors.white,
                                          ),
                                          child: Row(
                                            children: [
                                              SizedBox(width: 8,),
                                              Container(
                                                width: 100,
                                                height: 100,
                                                decoration: BoxDecoration(
                                                  borderRadius: BorderRadius.circular(20),
                                                ),
                                                child: Image.asset("assets/images/fc41cc1f5d4f47d9ab188c9a6112501e",fit: BoxFit.fill,),
                                              ),
                                              SizedBox(width: 8,),
                                              Column(
                                                children: [
                                                  SizedBox(height: 10,),
                                                  Container(
                                                    child: Text('Burger',style: TextStyle(
                                                      fontSize: 17,
                                                      fontWeight: FontWeight.w700,
                                                      fontFamily: 'Montserrat',
                                                    ),),
                                                  ),
                                                  SizedBox(height: 15,),
                                                  Container(
                                                    padding: EdgeInsets.only(right: 25),
                                                    child: Text('16 DT',style: TextStyle(
                                                      fontSize: 15,
                                                      fontWeight: FontWeight.w700,
                                                      fontFamily: 'Montserrat',
                                                    ),),
                                                  ),
                                                ],
                                              ),
                                              SizedBox(width: 80,),
                                              Column(
                                                children: [
                                                  SizedBox(height: 10,),
                                                  Container(
                                                    width: 100,
                                                    child: Row(
                                                      children: [
                                                        Container(
                                                          width : 25,
                                                            height: 20,
                                                            decoration: BoxDecoration(
                                                              color: AppColors.third,
                                                              borderRadius: BorderRadius.circular(40),
                                                            ),
                                                            child: Center(child: IconButton(onPressed: (){},icon: Icon(Icons.remove,size: 10,color: Colors.white,),))),
                                                        SizedBox(width: 8,),
                                                        Container(
                                                          child: Text('3'),
                                                        ),
                                                        SizedBox(width: 8,),
                                                        Container(
                                                            width : 25,
                                                            height: 20,
                                                            decoration: BoxDecoration(
                                                              color: AppColors.third,
                                                              borderRadius: BorderRadius.circular(40),
                                                            ),
                                                            child: Center(child: IconButton(onPressed: (){},icon: Icon(Icons.add,size: 10,color: Colors.white,),))),
                                                      ],
                                                    ),
                                                  ),
                                                  SizedBox(height: 20,),
                                                  Container(
                                                    child: Text('32 DT',
                                                    style: TextStyle(
                                                      fontSize: 15,
                                                      fontWeight: FontWeight.w700,
                                                      fontFamily: 'Montserrat',
                                                      color: Colors.black12,
                                                    ),),
                                                  ),
                                                ],
                                              ),
                                            ],
                                          ),
                                        ),
                                        SizedBox(height: 20,),

                                        Container(
                                          width: 380,
                                          height: 90,
                                          decoration: BoxDecoration(
                                            borderRadius: BorderRadius.circular(30),
                                            color: Colors.white,
                                          ),
                                          child: Row(
                                            children: [
                                              SizedBox(width: 8,),
                                              Container(
                                                width: 100,
                                                height: 100,
                                                decoration: BoxDecoration(
                                                  borderRadius: BorderRadius.circular(20),
                                                ),
                                                child: Image.asset("assets/images/fc41cc1f5d4f47d9ab188c9a6112501e",fit: BoxFit.fill,),
                                              ),
                                              SizedBox(width: 8,),
                                              Column(
                                                children: [
                                                  SizedBox(height: 10,),
                                                  Container(
                                                    child: Text('Burger',style: TextStyle(
                                                      fontSize: 17,
                                                      fontWeight: FontWeight.w700,
                                                      fontFamily: 'Montserrat',
                                                    ),),
                                                  ),
                                                  SizedBox(height: 15,),
                                                  Container(
                                                    padding: EdgeInsets.only(right: 25),
                                                    child: Text('16 DT',style: TextStyle(
                                                      fontSize: 15,
                                                      fontWeight: FontWeight.w700,
                                                      fontFamily: 'Montserrat',
                                                    ),),
                                                  ),
                                                ],
                                              ),
                                              SizedBox(width: 80,),
                                              Column(
                                                children: [
                                                  SizedBox(height: 10,),
                                                  Container(
                                                    width: 100,
                                                    child: Row(
                                                      children: [
                                                        Container(
                                                            width : 25,
                                                            height: 20,
                                                            decoration: BoxDecoration(
                                                              color: AppColors.third,
                                                              borderRadius: BorderRadius.circular(40),
                                                            ),
                                                            child: Center(child: IconButton(onPressed: (){},icon: Icon(Icons.remove,size: 10,color: Colors.white,),))),
                                                        SizedBox(width: 8,),
                                                        Container(
                                                          child: Text('3'),
                                                        ),
                                                        SizedBox(width: 8,),
                                                        Container(
                                                            width : 25,
                                                            height: 20,
                                                            decoration: BoxDecoration(
                                                              color: AppColors.third,
                                                              borderRadius: BorderRadius.circular(40),
                                                            ),
                                                            child: Center(child: IconButton(onPressed: (){},icon: Icon(Icons.add,size: 10,color: Colors.white,),))),
                                                      ],
                                                    ),
                                                  ),
                                                  SizedBox(height: 20,),
                                                  Container(
                                                    child: Text('32 DT',
                                                      style: TextStyle(
                                                        fontSize: 15,
                                                        fontWeight: FontWeight.w700,
                                                        fontFamily: 'Montserrat',
                                                        color: Colors.black12,
                                                      ),),
                                                  ),
                                                ],
                                              ),
                                            ],
                                          ),
                                        ),
                                        SizedBox(height: 20,),

                                        Container(
                                          width: 380,
                                          height: 90,
                                          decoration: BoxDecoration(
                                            borderRadius: BorderRadius.circular(30),
                                            color: Colors.white,
                                          ),
                                          child: Row(
                                            children: [
                                              SizedBox(width: 8,),
                                              Container(
                                                width: 100,
                                                height: 100,
                                                decoration: BoxDecoration(
                                                  borderRadius: BorderRadius.circular(20),
                                                ),
                                                child: Image.asset("assets/images/fc41cc1f5d4f47d9ab188c9a6112501e",fit: BoxFit.fill,),
                                              ),
                                              SizedBox(width: 8,),
                                              Column(
                                                children: [
                                                  SizedBox(height: 10,),
                                                  Container(
                                                    child: Text('Burger',style: TextStyle(
                                                      fontSize: 17,
                                                      fontWeight: FontWeight.w700,
                                                      fontFamily: 'Montserrat',
                                                    ),),
                                                  ),
                                                  SizedBox(height: 15,),
                                                  Container(
                                                    padding: EdgeInsets.only(right: 25),
                                                    child: Text('16 DT',style: TextStyle(
                                                      fontSize: 15,
                                                      fontWeight: FontWeight.w700,
                                                      fontFamily: 'Montserrat',
                                                    ),),
                                                  ),
                                                ],
                                              ),
                                              SizedBox(width: 80,),
                                              Column(
                                                children: [
                                                  SizedBox(height: 10,),
                                                  Container(
                                                    width: 100,
                                                    child: Row(
                                                      children: [
                                                        Container(
                                                            width : 25,
                                                            height: 20,
                                                            decoration: BoxDecoration(
                                                              color: AppColors.third,
                                                              borderRadius: BorderRadius.circular(40),
                                                            ),
                                                            child: Center(child: IconButton(onPressed: (){},icon: Icon(Icons.remove,size: 10,color: Colors.white,),))),
                                                        SizedBox(width: 8,),
                                                        Container(
                                                          child: Text('3'),
                                                        ),
                                                        SizedBox(width: 8,),
                                                        Container(
                                                            width : 25,
                                                            height: 20,
                                                            decoration: BoxDecoration(
                                                              color: AppColors.third,
                                                              borderRadius: BorderRadius.circular(40),
                                                            ),
                                                            child: Center(child: IconButton(onPressed: (){},icon: Icon(Icons.add,size: 10,color: Colors.white,),))),
                                                      ],
                                                    ),
                                                  ),
                                                  SizedBox(height: 20,),
                                                  Container(
                                                    child: Text('32 DT',
                                                      style: TextStyle(
                                                        fontSize: 15,
                                                        fontWeight: FontWeight.w700,
                                                        fontFamily: 'Montserrat',
                                                        color: Colors.black12,
                                                      ),),
                                                  ),
                                                ],
                                              ),
                                            ],
                                          ),
                                        ),
                                        SizedBox(height: 8,),
                                        const Divider(
                                          height: 20,
                                          thickness: 3,
                                          indent: 192,
                                          endIndent: 192,
                                          color: Colors.black12,
                                        ),
                                        SizedBox(height: 20,),

                                        Container(
                                          width: 380,
                                          height: 80,
                                          decoration: BoxDecoration(
                                            borderRadius: BorderRadius.circular(30),
                                            color: Colors.white,
                                          ),
                                          child: Row(
                                            children: [
                                              SizedBox(width: 20,),
                                              Icon(Icons.airplane_ticket_outlined,size: 30,color: Colors.black12,),
                                              SizedBox(width: 10,),
                                              Container(
                                                width: 200,
                                                child: TextField(
                                                  decoration: InputDecoration(
                                                    hintText: 'Promocode',
                                                    hintStyle: TextStyle(
                                                      fontSize: 20,
                                                      fontWeight: FontWeight.w700,
                                                      fontFamily: 'Montserrat',
                                                      color: Colors.black12,
                                                    )
                                                  ),
                                                ),
                                              ),
                                              SizedBox(width: 10,),
                                              Container(
                                                width: 100,
                                                child : RaisedButton(
                                                  onPressed: (){},
                                                  color: AppColors.third,
                                                  shape: RoundedRectangleBorder(
                                                      borderRadius: BorderRadius.circular(30)),
                                                  child: Text('Apply',style: TextStyle(
                                                    fontSize: 15,
                                                    fontWeight: FontWeight.w700,
                                                    fontFamily: 'Montserrat',
                                                    color: Colors.white,
                                                  ),),
                                                ),
                                              )
                                            ],
                                          ),
                                        ),
                                        SizedBox(height: 40,),
                                        Container(
                                          width: double.infinity,
                                          height: 190,
                                          decoration: BoxDecoration(
                                            borderRadius: BorderRadius.circular(20),
                                            color: Colors.white,
                                          ),
                                          child: Column(
                                            children: [
                                              SizedBox(height: 20,),
                                              Row(
                                                children: [
                                                  SizedBox(
                                                    width: 20,
                                                  ),
                                                  Text('Subtotal',style: TextStyle(
                                                    fontSize: 15,
                                                    fontWeight: FontWeight.w500,
                                                    fontFamily: 'Montserrat',
                                                    color: Colors.grey,
                                                  ),),
                                                  SizedBox(
                                                    width: 290,),
                                                  Text('83',style: TextStyle(
                                                    fontSize: 15,
                                                    fontWeight: FontWeight.w500,
                                                    fontFamily: 'Montserrat',
                                                    color: Colors.grey,
                                                  ),)
                                                ],
                                              ),
                                              const Divider(
                                                height: 20,
                                                thickness: 2,
                                                indent: 20,
                                                endIndent: 20,
                                                color: Colors.black12,
                                              ),
                                              Row(
                                                children: [
                                                  SizedBox(
                                                    width: 20,
                                                  ),
                                                  Text('Delivery',style: TextStyle(
                                                    fontSize: 15,
                                                    fontWeight: FontWeight.w500,
                                                    fontFamily: 'Montserrat',
                                                    color: Colors.grey,
                                                  ),),
                                                  SizedBox(
                                                    width: 290,),
                                                  Text('5',style: TextStyle(
                                                    fontSize: 15,
                                                    fontWeight: FontWeight.w500,
                                                    fontFamily: 'Montserrat',
                                                    color: Colors.grey,
                                                  ),)
                                                ],
                                              ),
                                              const Divider(
                                                height: 20,
                                                thickness: 2,
                                                indent: 20,
                                                endIndent: 20,
                                                color: Colors.black12,
                                              ),
                                              SizedBox(height: 10,),
                                              Row(
                                                children: [
                                                  SizedBox(
                                                    width: 20,
                                                  ),
                                                  Text('Total',style: TextStyle(
                                                    fontSize: 20,
                                                    fontWeight: FontWeight.w700,
                                                    fontFamily: 'Montserrat',
                                                    color: Colors.black,
                                                  ),),
                                                  SizedBox(
                                                    width: 290,),
                                                  Text('88',style: TextStyle(
                                                    fontSize: 20,
                                                    fontWeight: FontWeight.w700,
                                                    fontFamily: 'Montserrat',
                                                    color: Colors.black,
                                                  ),)
                                                ],
                                              ),
                                              SizedBox(height: 10,),
                                              Container(
                                                width: 200,
                                                height: 40,
                                                child: RaisedButton(
                                                  onPressed: (){},
                                                  color: AppColors.third,
                                                  shape: RoundedRectangleBorder(
                                                      borderRadius: BorderRadius.circular(30)),
                                                  child: Text('Pay',style: TextStyle(
                                                    fontSize: 15,
                                                    fontWeight: FontWeight.w700,
                                                    fontFamily: 'Montserrat',
                                                    color: Colors.white,
                                                  ),),
                                                ),
                                              )
                                            ],
                                          ),
                                        ),
                                      ],
                                    ),
                                  ]),
                            ))
                      ])),
                );
              }),
        ));
  }
}
