import 'package:flutter/material.dart';
import 'package:untitled5/theme/themee.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedEditEdit_Pencil_01Widget3.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedAvatarBackgroundWidget12.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedArrowCaret_Right_SMWidget21.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedVector25Widget11.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedInterfaceShopping_Bag_01Widget.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedArrowCaret_Right_SMWidget20.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedUserNamegmailcomWidget.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedArrowCaret_Right_SMWidget23.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedVectorWidget773.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedMyInformationsWidget.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedUserID184B756Widget.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedNotificationsWidget.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedMyProfileWidget.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedArrowCaret_Right_SMWidget22.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedMyOrdersWidget.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedLogOutWidget.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedUserUser_CloseWidget.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedInterfaceTicket_VoucherWidget.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedPromocodesWidget.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedWarningInfoWidget.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedAvatarWidget12.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedArrowCaret_Right_SMWidget19.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedAboutUsWidget.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedVectorWidget771.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedRectangle7Widget5.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedFiuserWidget3.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedRectangle2Widget6.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedCommunicationBell_NotificationWidget.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedArrowCaret_Right_SMWidget24.dart';
import 'package:untitled5/untitledapp/generatedaccountwidget/generated/GeneratedUserNameWidget.dart';

import '../helpers/svg/svg.dart';

/* Frame Account
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPromocodeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
                return SingleChildScrollView(
                  scrollDirection: Axis.vertical,
                  child: Container(
                      height: 930,
                      child: Stack(children: [
                        Container(
                            width: constraints.maxWidth,
                            child: Container(
                              width: 428.0,
                              height: 926.0,
                              child: Stack(
                                  clipBehavior: Clip.none, fit: StackFit.expand,
                                  alignment: Alignment.center,
                                  children: [
                                    ClipRRect(
                                      borderRadius: BorderRadius.zero,
                                      child: Container(
                                        color: Color.fromARGB(255, 255, 255, 255),
                                      ),
                                    ),
                                    Positioned(
                                      left: -1.0,
                                      top: 0.0,
                                      right: null,
                                      bottom: null,
                                      width: 429.0,
                                      height: 926.0,
                                      child: GeneratedRectangle2Widget6(),
                                    ),
                                    Positioned(
                                      left: 0.0,
                                      top: -51.0,
                                      right: null,
                                      bottom: null,
                                      width: 428.0,
                                      height: 347.0,
                                      child: GeneratedRectangle7Widget5(),
                                    ),
                                    Positioned(
                                      left: 311.0,
                                      top: -107.0,
                                      right: null,
                                      bottom: null,
                                      width: 239.564697265625,
                                      height: 251.9700164794922,
                                      child: GeneratedVectorWidget771(),
                                    ),
                                    Positioned(
                                      left: 372.0,
                                      top: 53.0,
                                      right: null,
                                      bottom: null,
                                      width: 34.0,
                                      height: 34.0,
                                      child: InkWell(onTap : (){},child: GeneratedEditEdit_Pencil_01Widget3()),
                                    ),
                                    Positioned(
                                      left: 145.0,
                                      top: 57.0,
                                      right: null,
                                      bottom: null,
                                      width: 140.0,
                                      height: 27.0,
                                      child: GeneratedMyProfileWidget(),
                                    ),
                                    Positioned(
                                      left: 170.0,
                                      top: 151.0,
                                      right: null,
                                      bottom: null,
                                      width: 144.0,
                                      height: 25.0,
                                      child: Container(
                                        width: 130,
                                        height: 60,
                                        child: Text('NAME ', style: TextStyle(
                                          fontSize: 25,
                                          fontWeight: FontWeight.w700,
                                          fontFamily: 'Montserrat',
                                        ),),
                                      ),
                                    ),
                                    Positioned(
                                      left: 170.0,
                                      top: 191.0,
                                      right: null,
                                      bottom: null,
                                      width: 206.0,
                                      height: 21.0,
                                      child: Container(
                                        width: 130,
                                        height: 60,
                                        child: Text('E-mail ', style: TextStyle(
                                          fontSize: 15,
                                          fontWeight: FontWeight.w500,
                                          fontFamily: 'Montserrat',
                                        ),),
                                      ),
                                    ),
                                    Positioned(
                                      left: 170.0,
                                      top: 223.0,
                                      right: null,
                                      bottom: null,
                                      width: 158.0,
                                      height: 18.0,
                                      child: Container(
                                        width: 130,
                                        height: 60,
                                        child: Text('User ID : ID ', style: TextStyle(
                                          fontSize: 15,
                                          fontWeight: FontWeight.w500,
                                          fontFamily: 'Montserrat',
                                        ),),
                                      ),
                                    ),
                                    Positioned(
                                      left: 22.0,
                                      top: 140.0,
                                      right: null,
                                      bottom: null,
                                      width: 104.0,
                                      height: 104.0,
                                      child: GeneratedAvatarBackgroundWidget12(),
                                    ),
                                    Positioned(
                                      left: 19.0,
                                      top: 149.0,
                                      right: null,
                                      bottom: null,
                                      width: 103.0,
                                      height: 101.0,
                                      child: GeneratedAvatarWidget12(),
                                    ),
                                    Positioned(
                                      left: 134.546875,
                                      top: 1032.8741455078125,
                                      right: null,
                                      bottom: null,
                                      width: 239.564697265625,
                                      height: 251.9700164794922,
                                      child: GeneratedVectorWidget773(),
                                    ),
                                    Column(
                                      children: [
                                        SizedBox(height: 330,),
                                        Row(
                                          children: [
                                            InkWell(onTap : (){} , child: Container(
                                              margin: EdgeInsets.only(left: 110),
                                              width: 300,
                                              height: 70,
                                              child: Row(
                                                children: [
                                                  Container(
                                                    width: 40,
                                                    height: 40,
                                                    child: GeneratedInterfaceTicket_VoucherWidget(),
                                                  ),
                                                  Container(
                                                    width: 150,
                                                    height: 70,
                                                    margin: EdgeInsets.only(top: 25),
                                                    child: GeneratedPromocodesWidget(),
                                                  ),
                                                ],
                                              ),
                                            )),
                                          ],
                                        ),
                                        SizedBox(height: 10,),
                                        Container(
                                          width: 380,
                                          height: 350,
                                          decoration: BoxDecoration(
                                            color: Colors.white,
                                            borderRadius: BorderRadius.circular(40),
                                          ),
                                          child:
                                          Column(
                                            children: [
                                              SizedBox(height: 20,),
                                              Container(
                                                height: 50,
                                                width: 300,
                                                child: TextFormField(
                                                  decoration: const InputDecoration(
                                                    border: UnderlineInputBorder(),
                                                    labelText: 'Enter A Valid Promocode',
                                                    labelStyle: TextStyle(
                                                      fontSize: 16,
                                                      fontWeight: FontWeight.w200,
                                                      fontFamily: 'Montserrat',
                                                      color: Colors.grey,
                                                    ),
                                                    icon: Icon(Icons.credit_card_rounded),
                                                ),
                                              ),
                                              ),
                                              SizedBox(height: 200,),
                                              Container(
                                                width: 170,
                                                height: 40,
                                                child: RaisedButton(onPressed: (){},
                                                  color: AppColors.third,
                                                  shape: RoundedRectangleBorder(
                                                      borderRadius: BorderRadius.circular(30)),
                                                  child:
                                                  Text('Apply',style: TextStyle(
                                                    fontSize: 18,
                                                    fontWeight: FontWeight.w700,
                                                    fontFamily: 'Montserrat',
                                                    color: Colors.white,
                                                  ),),),
                                              )
                                            ],
                                          ),
                                        ),

                                      ],
                                    ),
                                    Positioned(
                                      left: 7.0,
                                      top: 50.0,
                                      right: null,
                                      bottom: null,
                                      width: 70,
                                      height: 40,
                                      child: IconButton(onPressed: (){},icon: Icon(Icons.arrow_back,size: 30,color: Colors.black54,),),
                                    ),
                                  ]),
                            ))
                      ])),
                );
              }),
        ));
  }
}
