import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generatedcartemptywidget/generated/GeneratedRectangle1Widget26.dart';
import 'package:untitled5/untitledapp/generatedcartemptywidget/generated/GeneratedVectorWidget755.dart';
import 'package:untitled5/untitledapp/generatedcartemptywidget/generated/GeneratedInterfaceShopping_Cart_01Widget4.dart';
import 'package:untitled5/untitledapp/generatedcartemptywidget/generated/GeneratedAvatarBackgroundWidget7.dart';
import 'package:untitled5/untitledapp/generatedcartemptywidget/generated/GeneratedAvatarWidget7.dart';
import 'package:untitled5/untitledapp/generatedcartemptywidget/generated/GeneratedArrowCaret_Right_SMWidget14.dart';
import 'package:untitled5/untitledapp/generatedcartemptywidget/generated/GeneratedA28SecondFloorSector64Noida20130102Widget8.dart';
import 'package:untitled5/untitledapp/generatedcartemptywidget/generated/GeneratedDelivertoWidget4.dart';
import 'package:untitled5/untitledapp/generatedsendemailwidget/generated/GeneratedWavy_Tech28_Single10Converted1Widget.dart';

import '../../theme/themee.dart';

/* Frame Cart Empty
    Autogenerated by FlutLab FTF Generator
  */
class Payment extends StatefulWidget {
  const Payment({Key? key}) : super(key: key);

  @override
  State<Payment> createState() => _PaymentState();
}

class _PaymentState extends State<Payment> {
  var value = false;
  var value2 = false;
  var value3 = false;
  var value4 = false;
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
                return SingleChildScrollView(
                  scrollDirection: Axis.vertical,
                  child: Container(
                      height: 1130.0,
                      color: AppColors.seven,
                      child: Stack(children: [
                        Container(
                            width: constraints.maxWidth,
                            color: AppColors.seven,
                            child: Container(
                              width: 428.0,
                              height: 1130.0,
                              color: AppColors.seven,
                              child: Stack(
                                  clipBehavior: Clip.none, fit: StackFit.expand,
                                  alignment: Alignment.center,
                                  children: [
                                    ClipRRect(
                                      borderRadius: BorderRadius.zero,
                                      child: Container(
                                        color: AppColors.six,
                                      ),
                                    ),
                                    Positioned(
                                      left: -1.0,
                                      top: 0.0,
                                      right: null,
                                      bottom: null,
                                      width: 429.0,
                                      height: 926.0,
                                      child: GeneratedRectangle1Widget26(),
                                    ),
                                    Positioned(
                                      left: 19.0,
                                      top: 40.0,
                                      right: null,
                                      bottom: null,
                                      width: 58.0,
                                      height: 58.0,
                                      child: GeneratedAvatarBackgroundWidget7(),
                                    ),
                                    Positioned(
                                      left: 19.0,
                                      top: 43.0,
                                      right: null,
                                      bottom: null,
                                      width: 59.0,
                                      height: 59.0,
                                      child: GeneratedAvatarWidget7(),
                                    ),
                                    Positioned(
                                      left: 172.0,
                                      top: 47.0,
                                      right: null,
                                      bottom: null,
                                      width: 87.0,
                                      height: 17.0,
                                      child: GeneratedDelivertoWidget4(),
                                    ),
                                    Positioned(
                                      left: 109.0,
                                      top: 66.0,
                                      right: null,
                                      bottom: null,
                                      width: 212.0,
                                      height: 30.0,
                                      child:
                                      GeneratedA28SecondFloorSector64Noida20130102Widget8(),
                                    ),
                                    Positioned(
                                      left: 278.9794921875,
                                      top: 41.0,
                                      right: null,
                                      bottom: null,
                                      width: 27.979501724243164,
                                      height: 27.979501724243164,
                                      child: GeneratedArrowCaret_Right_SMWidget14(),
                                    ),
                                    Positioned(
                                      left: 328.0,
                                      top: -116.0,
                                      right: null,
                                      bottom: null,
                                      width: 239.564697265625,
                                      height: 251.9700164794922,
                                      child: GeneratedVectorWidget755(),
                                    ),
                                    Positioned(
                                      left: 358.0,
                                      top: 50.0,
                                      right: null,
                                      bottom: null,
                                      width: 43.0,
                                      height: 43.0,
                                      child:
                                      InkWell(onTap : (){} ,child: GeneratedInterfaceShopping_Cart_01Widget4()),
                                    ),
                                    Column(
                                      children: [
                                        SizedBox(height: 190,),
                                        Row(
                                            children:[ Container(
                                              margin: EdgeInsets.only(right: 120),
                                              child: IconButton(
                                                icon: Icon(Icons.arrow_back,size: 30,color: Colors.grey,),
                                                onPressed: (){},
                                              ),
                                            ),
                                              Text('Payment',style: TextStyle(
                                                fontSize: 25,
                                                fontWeight: FontWeight.w500,
                                                fontFamily: 'Montserrat',
                                                color: Colors.grey.withOpacity(0.7),
                                              ),)
                                            ]
                                        ),
                                        SizedBox(height: 20,),
                                        Row(
                                          children: [
                                            SizedBox(width: 40,),
                                            Text('Shipping to',style: TextStyle(
                                              fontSize: 20,
                                              fontWeight: FontWeight.w700,
                                              fontFamily: 'Montserrat',
                                            ),),
                                            SizedBox(width: 180,),
                                            IconButton(onPressed: (){}, icon:Icon(Icons.edit_outlined,size: 30,color: Colors.black,)),
                                          ],
                                        ),
                                        SizedBox(height: 20,),
                                        Container(
                                          width: 380,
                                          height: 70,
                                          decoration: BoxDecoration(
                                            borderRadius: BorderRadius.circular(30),
                                            border: Border.all(color: AppColors.third),
                                            color: Colors.white,
                                          ),
                                          child: Row(
                                            children: [
                                              SizedBox(width: 10,),
                                              Checkbox(
                                                value: this.value,
                                                activeColor: AppColors.first,
                                                shape: CircleBorder(),
                                                onChanged: (value) {
                                                  setState(() {
                                                    this.value = value!;
                                                  });
                                                },),
                                              SizedBox(width: 10,),
                                              Icon(Icons.work_outline_outlined,size: 30,color: Colors.grey,),
                                              SizedBox(width: 10,),
                                              Text('Send To My Office',style: TextStyle(
                                                fontSize: 20,
                                                fontWeight: FontWeight.w700,
                                                fontFamily: 'Montserrat',
                                                color: Colors.grey,
                                              ),),
                                            ],
                                          ),
                                        ),
                                        SizedBox(height: 20,),

                                        Container(
                                          width: 380,
                                          height: 70,
                                          decoration: BoxDecoration(
                                            borderRadius: BorderRadius.circular(30),
                                            border: Border.all(color: AppColors.third),
                                            color: Colors.white,
                                          ),
                                          child: Row(
                                            children: [
                                              SizedBox(width: 10,),
                                              Checkbox(
                                                value: this.value2,
                                                activeColor: AppColors.first,
                                                shape: CircleBorder(),
                                                onChanged: (value) {
                                                  setState(() {
                                                    this.value2 = value!;
                                                  });
                                                },),
                                              SizedBox(width: 10,),
                                              Icon(Icons.home_outlined,size: 30,color: Colors.grey,),
                                              SizedBox(width: 10,),
                                              Text('Send To My Home',style: TextStyle(
                                                fontSize: 20,
                                                fontWeight: FontWeight.w700,
                                                fontFamily: 'Montserrat',
                                                color: Colors.grey,
                                              ),),
                                            ],
                                          ),
                                        ),
                                        SizedBox(height: 8,),
                                        const Divider(
                                          height: 20,
                                          thickness: 3,
                                          indent: 192,
                                          endIndent: 192,
                                          color: Colors.black12,
                                        ),
                                        SizedBox(height: 20,),
                                        Row(
                                          children: [
                                            SizedBox(width: 40,),
                                            Text('Payment Method',style: TextStyle(
                                              fontSize: 20,
                                              fontWeight: FontWeight.w700,
                                              fontFamily: 'Montserrat',
                                            ),),
                                            SizedBox(width: 120,),
                                            IconButton(onPressed: (){}, icon:Icon(Icons.edit_outlined,size: 30,color: Colors.black,)),
                                          ],
                                        ),
                                        SizedBox(height: 20,),
                                        Container(
                                          width: 380,
                                          height: 90,
                                          decoration: BoxDecoration(
                                            borderRadius: BorderRadius.circular(20),
                                            color: Colors.white,
                                          ),
                                          child: Row(
                                            children: [
                                              SizedBox(width: 40,),
                                              Icon(Icons.credit_card_rounded,size: 30,color: Colors.grey,),
                                              SizedBox(width: 10,),
                                              Text('Credit Card',style: TextStyle(
                                                fontSize: 20,
                                                fontWeight: FontWeight.w700,
                                                fontFamily: 'Montserrat',
                                                color: Colors.grey,
                                              ),),
                                              SizedBox(width: 120,),
                                              Checkbox(
                                                value: this.value3,
                                                activeColor: AppColors.first,
                                                shape: CircleBorder(),
                                                onChanged: (value) {
                                                  setState(() {
                                                    this.value3 = value!;
                                                  });
                                                },),
                                            ],
                                          ),
                                        ),
                                        SizedBox(height: 20,),
                                        Container(
                                          width: 380,
                                          height: 90,
                                          decoration: BoxDecoration(
                                            borderRadius: BorderRadius.circular(20),
                                            color: Colors.white,
                                          ),
                                          child: Row(
                                            children: [
                                              SizedBox(width: 40,),
                                              Icon(Icons.payments_outlined,size: 30,color: Colors.grey,),
                                              SizedBox(width: 10,),
                                              Text('Cash Payment',style: TextStyle(
                                                fontSize: 20,
                                                fontWeight: FontWeight.w700,
                                                fontFamily: 'Montserrat',
                                                color: Colors.grey,
                                              ),),
                                              SizedBox(width: 90,),
                                              Checkbox(
                                                value: this.value4,
                                                activeColor: AppColors.first,
                                                shape: CircleBorder(),
                                                onChanged: (value) {
                                                  setState(() {
                                                    this.value4 = value!;
                                                  });
                                                },),
                                            ],
                                          ),
                                        ),
                                        SizedBox(height: 8,),
                                        const Divider(
                                          height: 20,
                                          thickness: 3,
                                          indent: 192,
                                          endIndent: 192,
                                          color: Colors.black12,
                                        ),
                                        SizedBox(height: 10,),
                                        Container(
                                          width: double.infinity,
                                          height: 290,
                                          color: AppColors.seven,
                                          child: Column(
                                            children: [
                                              SizedBox(height: 10,),
                                              const Divider(
                                                height: 20,
                                                thickness: 2,
                                                indent: 20,
                                                endIndent: 20,
                                                color: Colors.black12,
                                              ),
                                              SizedBox(height: 10,),
                                              Row(
                                                children: [
                                                  SizedBox(
                                                    width: 20,
                                                  ),
                                                  Text('items',style: TextStyle(
                                                    fontSize: 15,
                                                    fontWeight: FontWeight.w500,
                                                    fontFamily: 'Montserrat',
                                                    color: Colors.grey,
                                                  ),),
                                                  SizedBox(
                                                    width: 290,),
                                                  Text('5',style: TextStyle(
                                                    fontSize: 15,
                                                    fontWeight: FontWeight.w500,
                                                    fontFamily: 'Montserrat',
                                                    color: Colors.grey,
                                                  ),)
                                                ],
                                              ),
                                              SizedBox(height: 30,),
                                              Row(
                                                children: [
                                                  SizedBox(
                                                    width: 20,
                                                  ),
                                                  Text('Discount',style: TextStyle(
                                                    fontSize: 15,
                                                    fontWeight: FontWeight.w500,
                                                    fontFamily: 'Montserrat',
                                                    color: Colors.grey,
                                                  ),),
                                                  SizedBox(
                                                    width: 250,),
                                                  Text('20%',style: TextStyle(
                                                    fontSize: 15,
                                                    fontWeight: FontWeight.w500,
                                                    fontFamily: 'Montserrat',
                                                    color: Colors.grey,
                                                  ),)
                                                ],
                                              ),
                                              const Divider(
                                                height: 20,
                                                thickness: 2,
                                                indent: 20,
                                                endIndent: 20,
                                                color: Colors.black12,
                                              ),
                                              SizedBox(height: 30,),
                                              Row(
                                                children: [
                                                  SizedBox(
                                                    width: 20,
                                                  ),
                                                  Text('Total',style: TextStyle(
                                                    fontSize: 20,
                                                    fontWeight: FontWeight.w500,
                                                    fontFamily: 'Montserrat',
                                                    color: Colors.black,
                                                  ),),
                                                  SizedBox(
                                                    width: 250,),
                                                  Text('20 DT',style: TextStyle(
                                                    fontSize: 20,
                                                    fontWeight: FontWeight.w500,
                                                    fontFamily: 'Montserrat',
                                                    color: Colors.black,
                                                  ),),

                                                ],
                                              ),
                                              SizedBox(height: 50,),
                                              Container(
                                                width: 200,
                                                height: 40,
                                                child: RaisedButton(
                                                  onPressed: ()async {
                                                    await  showDialog(
                                                        context: context,
                                                        builder: (BuildContext context) {
                                                          return AlertDialog(
                                                            scrollable: true,
                                                            shape: RoundedRectangleBorder(borderRadius:
                                                            BorderRadius.all(Radius.circular(40))),
                                                            content: Padding(
                                                                padding: const EdgeInsets.all(8.0),
                                                                child: Column(
                                                                  children: [
                                                                    SizedBox(height: 30,),
                                                                    Container(
                                                                      margin: EdgeInsets.only(left: 30,bottom: 20),
                                                                      child: ClipRRect(
                                                                        borderRadius: BorderRadius.circular(20.0),
                                                                        child: Image.asset(
                                                                          "assets/images/1a22c7938bb82192387bd7c069138ca1592f1343.png",
                                                                          height: 250,
                                                                          width: 250,
                                                                          fit: BoxFit.fitWidth,
                                                                        ),
                                                                      ),
                                                                    ),
                                                                    SizedBox(height:
                                                                    20,),
                                                                    Container(
                                                                      width: 250,
                                                                      child: Center(
                                                                        child: Text('You’ll be getting a call ',textAlign: TextAlign.center,
                                                                          style: TextStyle(
                                                                            fontSize: 20,
                                                                            fontWeight: FontWeight.w700,
                                                                            fontFamily: 'Montserrat',
                                                                          ),),
                                                                      ),
                                                                    ),
                                                                    Container(
                                                                      width: 250,
                                                                      child: Center(
                                                                        child: Text('from  us  soon!',textAlign: TextAlign.center,
                                                                          style: TextStyle(
                                                                            fontSize: 20,
                                                                            fontWeight: FontWeight.w700,
                                                                            fontFamily: 'Montserrat',
                                                                          ),),
                                                                      ),
                                                                    ),
                                                                    SizedBox(height:
                                                                    20,),
                                                                    Container(
                                                                      width: 500,
                                                                      height: 50,
                                                                      child: Center(
                                                                        child: RaisedButton(
                                                                          color: AppColors.third,
                                                                          shape: RoundedRectangleBorder(
                                                                              borderRadius: BorderRadius.circular(30)),
                                                                          onPressed: (){},
                                                                          child: Text('Confirm and go back to shopping',
                                                                            style: TextStyle(
                                                                              fontSize: 12,
                                                                              fontWeight: FontWeight.w500,
                                                                              fontFamily: 'Montserrat',
                                                                              color: Colors.white,
                                                                            ),
                                                                          ),
                                                                        ),),),
                                                                    Container(
                                                                      width: 150,
                                                                      height: 30,
                                                                      margin: EdgeInsets.only(left: 5),
                                                                      child: InkWell(onTap: (){
                                                                        Navigator.pop(context);
                                                                      },
                                                                        child: Center(
                                                                          child: Text(
                                                                            'Cancel',style: TextStyle(
                                                                            fontSize: 15,
                                                                            color: Colors.grey,
                                                                            fontWeight: FontWeight.w500,
                                                                            fontFamily: 'Montserrat',
                                                                          ),
                                                                          ),
                                                                        ),
                                                                      ),),
                                                                  ],
                                                                )
                                                            ),
                                                          );
                                                        });
                                                  },
                                                  shape: RoundedRectangleBorder(
                                                      borderRadius: BorderRadius.circular(30)),
                                                  color: AppColors.third,
                                                  child: Center(
                                                    child: Text('CHECKOUT',style: TextStyle(
                                                      fontSize: 25,
                                                      fontWeight: FontWeight.w700,
                                                      fontFamily: 'Montserrat',
                                                      color: Colors.white,
                                                    ),),
                                                  ),
                                                ),
                                              )
                                            ],
                                          ),
                                        ),
                                      ],
                                    ),
                                  ]),
                            ))
                      ])),
                );
              }),
        ));
  }
}
