import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generatedaboutuswidget1/generated/GeneratedVector25Widget17.dart';
import 'package:untitled5/untitledapp/generatedaboutuswidget1/generated/GeneratedVectorWidget800.dart';
import 'package:untitled5/untitledapp/generatedaboutuswidget1/generated/GeneratedVectorWidget801.dart';
import 'package:untitled5/untitledapp/generatedaboutuswidget1/generated/GeneratedAboutUsWidget2.dart';
import 'package:untitled5/untitledapp/generatedaboutuswidget1/generated/GeneratedLoremipsumdolorsitametconsectetueradipiscingelitseddiam.dart';
import 'package:untitled5/untitledapp/generatedaboutuswidget1/generated/GeneratedRectangle2Widget12.dart';
import 'package:untitled5/untitledapp/generatedaboutuswidget1/generated/Generated26723331Widget.dart';

/* Frame About Us
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAboutUsWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 930,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none, fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle2Widget12(),
                            ),
                            Positioned(
                              left: 311.0,
                              top: -107.0,
                              right: null,
                              bottom: null,
                              width: 239.564697265625,
                              height: 251.9700164794922,
                              child: GeneratedVectorWidget800(),
                            ),
                            Positioned(
                              left: 151.0,
                              top: 57.0,
                              right: null,
                              bottom: null,
                              width: 129.0,
                              height: 27.0,
                              child: GeneratedAboutUsWidget2(),
                            ),
                            Positioned(
                              left: 134.546875,
                              top: 1043.8740234375,
                              right: null,
                              bottom: null,
                              width: 239.564697265625,
                              height: 251.9700164794922,
                              child: GeneratedVectorWidget801(),
                            ),
                            Positioned(
                              left: 6.0,
                              top: 173.0,
                              right: null,
                              bottom: null,
                              width: 396.0,
                              height: 290.0,
                              child: Generated26723331Widget(),
                            ),
                            Positioned(
                              left: 49.0,
                              top: 516.0,
                              right: null,
                              bottom: null,
                              width: 344.0,
                              height: 247.0,
                              child:
                                  Container(
                                    child: Text('All Informations Are Here',
                                    style: TextStyle(
                                      fontSize: 25,
                                      fontWeight: FontWeight.w200,
                                      fontFamily: 'Montserrat',
                                    ),),
                                  ),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 50.0,
                              right: null,
                              bottom: null,
                              width: 42.0,
                              height: 40,
                              child: IconButton(onPressed: (){},icon: Icon(Icons.arrow_back,size: 30,color: Colors.grey,),),
                            ),
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
