import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generatedcartemptywidget/generated/GeneratedRectangle1Widget26.dart';
import 'package:untitled5/untitledapp/generatedcartemptywidget/generated/GeneratedVectorWidget755.dart';
import 'package:untitled5/untitledapp/generatedcartemptywidget/generated/GeneratedInterfaceShopping_Cart_01Widget4.dart';
import 'package:untitled5/untitledapp/generatedcartemptywidget/generated/GeneratedAvatarBackgroundWidget7.dart';
import 'package:untitled5/untitledapp/generatedcartemptywidget/generated/GeneratedAvatarWidget7.dart';
import 'package:untitled5/untitledapp/generatedcartemptywidget/generated/GeneratedArrowCaret_Right_SMWidget14.dart';
import 'package:untitled5/untitledapp/generatedcartemptywidget/generated/GeneratedA28SecondFloorSector64Noida20130102Widget8.dart';
import 'package:untitled5/untitledapp/generatedcartemptywidget/generated/GeneratedDelivertoWidget4.dart';
import 'package:untitled5/untitledapp/generatedsendemailwidget/generated/GeneratedWavy_Tech28_Single10Converted1Widget.dart';

import '../../theme/themee.dart';

/* Frame Cart Empty
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCartEmptyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              color: AppColors.six,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none, fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: AppColors.six,
                              ),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle1Widget26(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 40.0,
                              right: null,
                              bottom: null,
                              width: 58.0,
                              height: 58.0,
                              child: GeneratedAvatarBackgroundWidget7(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 43.0,
                              right: null,
                              bottom: null,
                              width: 59.0,
                              height: 59.0,
                              child: GeneratedAvatarWidget7(),
                            ),
                            Positioned(
                              left: 172.0,
                              top: 47.0,
                              right: null,
                              bottom: null,
                              width: 87.0,
                              height: 17.0,
                              child: GeneratedDelivertoWidget4(),
                            ),
                            Positioned(
                              left: 109.0,
                              top: 66.0,
                              right: null,
                              bottom: null,
                              width: 212.0,
                              height: 30.0,
                              child:
                                  GeneratedA28SecondFloorSector64Noida20130102Widget8(),
                            ),
                            Positioned(
                              left: 278.9794921875,
                              top: 41.0,
                              right: null,
                              bottom: null,
                              width: 27.979501724243164,
                              height: 27.979501724243164,
                              child: GeneratedArrowCaret_Right_SMWidget14(),
                            ),
                            Positioned(
                              left: 328.0,
                              top: -116.0,
                              right: null,
                              bottom: null,
                              width: 239.564697265625,
                              height: 251.9700164794922,
                              child: GeneratedVectorWidget755(),
                            ),
                            Positioned(
                              left: 358.0,
                              top: 50.0,
                              right: null,
                              bottom: null,
                              width: 43.0,
                              height: 43.0,
                              child:
                                  InkWell(onTap : (){} ,child: GeneratedInterfaceShopping_Cart_01Widget4()),
                            ),
                            Column(
                              children: [
                                SizedBox(height: 190,),
                                Row(
                                  children:[ Container(
                                    margin: EdgeInsets.only(right: 130),
                                    child: IconButton(
                                      icon: Icon(Icons.arrow_back,size: 30,color: Colors.grey,),
                                      onPressed: (){},
                                    ),
                                  ),
                                    Text('Cart',style: TextStyle(
                                      fontSize: 25,
                                      fontWeight: FontWeight.w500,
                                      fontFamily: 'Montserrat',
                                      color: Colors.grey.withOpacity(0.7),
                                    ),)
                                  ]
                                ),
                                SizedBox(height: 20,),
                                ClipRRect(
                                  borderRadius: BorderRadius.circular(20.0),
                                  child: Image.asset(
                                    "assets/images/c65503a59efe8e513cdbe7137a43b7acd8d66fbe.png",
                                    height: 350,
                                    width: 350,
                                    fit: BoxFit.fitWidth,
                                  ),
                                ),
                                SizedBox(height: 40,),
                                Container(
                                  child: Center(
                                    child: Text('It Appears that your ',style: TextStyle(
                                      fontSize: 25,
                                      fontWeight: FontWeight.w700,
                                      fontFamily: 'Montserrat',
                                    ),),
                                  ),
                                ),
                                Container(
                                  child: Center(
                                    child: Text('Shopping Cart is',style: TextStyle(
                                      fontSize: 25,
                                      fontWeight: FontWeight.w700,
                                      fontFamily: 'Montserrat',
                                    ),),
                                  ),
                                ),
                                Container(
                                  child: Center(
                                    child: Text('empty!',style: TextStyle(
                                      fontSize: 25,
                                      fontWeight: FontWeight.w700,
                                      fontFamily: 'Montserrat',
                                    ),),
                                  ),
                                ),
                                SizedBox(height: 40,),
                                Container(
                                  width: 300,
                                  height: 40,
                                  child: RaisedButton(
                                    onPressed: (){},
                                    shape: RoundedRectangleBorder(
                                        borderRadius: BorderRadius.circular(30)),
                                    color: AppColors.third,
                                    child: Center(
                                      child: Text('Start Ordering',style: TextStyle(
                                        fontSize: 25,
                                        fontWeight: FontWeight.w700,
                                        fontFamily: 'Montserrat',
                                        color: Colors.white,
                                      ),),
                                    ),
                                  ),
                                )
                              ],
                            ),

                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
