import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generatedinfowidget/generated/GeneratedUserNamegmailcomWidget1.dart';
import 'package:untitled5/untitledapp/generatedinfowidget/generated/GeneratedMyInformationsWidget1.dart';
import 'package:untitled5/untitledapp/generatedinfowidget/generated/GeneratedProfilePictureWidget.dart';
import 'package:untitled5/untitledapp/generatedinfowidget/generated/GeneratedFiuserWidget4.dart';
import 'package:untitled5/untitledapp/generatedinfowidget/generated/GeneratedRectangle8Widget11.dart';
import 'package:untitled5/untitledapp/generatedinfowidget/generated/GeneratedEditEdit_Pencil_01Widget4.dart';
import 'package:untitled5/untitledapp/generatedinfowidget/generated/GeneratedPhoneNumber21699999999Widget.dart';
import 'package:untitled5/untitledapp/generatedinfowidget/generated/GeneratedEmailAdressUsernamegmailcomWidget.dart';
import 'package:untitled5/untitledapp/generatedinfowidget/generated/GeneratedVectorWidget795.dart';
import 'package:untitled5/untitledapp/generatedinfowidget/generated/GeneratedAvatarWidget14.dart';
import 'package:untitled5/untitledapp/generatedinfowidget/generated/GeneratedVectorWidget797.dart';
import 'package:untitled5/untitledapp/generatedinfowidget/generated/GeneratedRectangle7Widget6.dart';
import 'package:untitled5/untitledapp/generatedinfowidget/generated/GeneratedRectangle2Widget11.dart';
import 'package:untitled5/untitledapp/generatedinfowidget/generated/GeneratedUserID184B756Widget1.dart';
import 'package:untitled5/untitledapp/generatedinfowidget/generated/GeneratedAvatarBackgroundWidget14.dart';
import 'package:untitled5/untitledapp/generatedinfowidget/generated/GeneratedAvatarWidget13.dart';
import 'package:untitled5/untitledapp/generatedinfowidget/generated/GeneratedUserNameWidget1.dart';
import 'package:untitled5/untitledapp/generatedinfowidget/generated/GeneratedVector25Widget16.dart';
import 'package:untitled5/untitledapp/generatedinfowidget/generated/GeneratedAddressLocationTunisTunisiaWidget.dart';
import 'package:untitled5/untitledapp/generatedinfowidget/generated/GeneratedAvatarBackgroundWidget13.dart';
import 'package:untitled5/untitledapp/generatedinfowidget/generated/GeneratedMyProfileWidget1.dart';
import 'package:untitled5/untitledapp/generatedinfowidget/generated/GeneratedFullNameNameSurnameWidget.dart';

/* Frame Info
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInfoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1284.8441619873047,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none, fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle2Widget11(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -51.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 347.0,
                              child: GeneratedRectangle7Widget6(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 425.0,
                              right: null,
                              bottom: null,
                              width: 387.0,
                              height: 309.0,
                              child: GeneratedRectangle8Widget11(),
                            ),
                            Positioned(
                              left: 311.0,
                              top: -107.0,
                              right: null,
                              bottom: null,
                              width: 239.564697265625,
                              height: 251.9700164794922,
                              child: GeneratedVectorWidget795(),
                            ),
                            Positioned(
                              left: 372.0,
                              top: 53.0,
                              right: null,
                              bottom: null,
                              width: 34.0,
                              height: 34.0,
                              child: GeneratedEditEdit_Pencil_01Widget4(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 70.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 0.0,
                              child: GeneratedVector25Widget16(),
                            ),
                            Positioned(
                              left: 145.0,
                              top: 57.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 27.0,
                              child: GeneratedMyProfileWidget1(),
                            ),
                            Positioned(
                              left: 141.0,
                              top: 351.0,
                              right: null,
                              bottom: null,
                              width: 211.0,
                              height: 25.0,
                              child: GeneratedMyInformationsWidget1(),
                            ),
                            Positioned(
                              left: 145.0,
                              top: 151.0,
                              right: null,
                              bottom: null,
                              width: 144.0,
                              height: 25.0,
                              child: GeneratedUserNameWidget1(),
                            ),
                            Positioned(
                              left: 145.0,
                              top: 191.0,
                              right: null,
                              bottom: null,
                              width: 206.0,
                              height: 21.0,
                              child: GeneratedUserNamegmailcomWidget1(),
                            ),
                            Positioned(
                              left: 145.0,
                              top: 223.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 18.0,
                              child: GeneratedUserID184B756Widget1(),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 140.0,
                              right: null,
                              bottom: null,
                              width: 104.0,
                              height: 104.0,
                              child: GeneratedAvatarBackgroundWidget13(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 446.0,
                              right: null,
                              bottom: null,
                              width: 76.0,
                              height: 76.0,
                              child: GeneratedAvatarBackgroundWidget14(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 149.0,
                              right: null,
                              bottom: null,
                              width: 103.0,
                              height: 101.0,
                              child: GeneratedAvatarWidget13(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 452.0,
                              right: null,
                              bottom: null,
                              width: 75.0,
                              height: 74.0,
                              child: GeneratedAvatarWidget14(),
                            ),
                            Positioned(
                              left: 134.546875,
                              top: 1032.8741455078125,
                              right: null,
                              bottom: null,
                              width: 239.564697265625,
                              height: 251.9700164794922,
                              child: GeneratedVectorWidget797(),
                            ),
                            Positioned(
                              left: 84.0,
                              top: 342.0,
                              right: null,
                              bottom: null,
                              width: 40.0,
                              height: 40.0,
                              child: GeneratedFiuserWidget4(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 548.0,
                              right: null,
                              bottom: null,
                              width: 260.0,
                              height: 19.0,
                              child: GeneratedFullNameNameSurnameWidget(),
                            ),
                            Positioned(
                              left: 132.0,
                              top: 480.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 19.0,
                              child: GeneratedProfilePictureWidget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 594.0,
                              right: null,
                              bottom: null,
                              width: 356.0,
                              height: 19.0,
                              child:
                                  GeneratedEmailAdressUsernamegmailcomWidget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 640.0,
                              right: null,
                              bottom: null,
                              width: 310.0,
                              height: 19.0,
                              child: GeneratedPhoneNumber21699999999Widget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 686.0,
                              right: null,
                              bottom: null,
                              width: 313.0,
                              height: 19.0,
                              child:
                                  GeneratedAddressLocationTunisTunisiaWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
