import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/GeneratedCodephoneWidget.dart';
import 'package:untitled5/untitledapp/generatedsendphonewidget/generated/GeneratedFrameWidget5.dart';
import 'package:untitled5/untitledapp/generatedsendphonewidget/generated/GeneratedPleaseEnterYourPhoneNumberToRecieveaVerificationCodeWid.dart';
import 'package:untitled5/untitledapp/generatedsendphonewidget/generated/GeneratedRectangle1Widget11.dart';
import 'package:untitled5/untitledapp/generatedsendphonewidget/generated/GeneratedRectangle8Widget3.dart';
import 'package:untitled5/untitledapp/generatedsendphonewidget/generated/GeneratedSendCodeWidget1.dart';
import 'package:untitled5/untitledapp/generatedsendphonewidget/generated/GeneratedVector26Widget1.dart';
import 'package:untitled5/untitledapp/generatedsendphonewidget/generated/GeneratedWavy_Tech28_Single10Converted11Widget.dart';

import '../../helpers/transform/transform.dart';
import '../../theme/themee.dart';
import '../generatedsigninwidget/generated/GeneratedPhoneWidget.dart';
import 'generated/GeneratedForgotPasswordWidget1.dart';
import 'generated/GeneratedPHONENUMBERWidget.dart';
import 'generated/GeneratedVector25Widget5.dart';

/* Frame Send phone
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSendphoneWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none, fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 98.0,
                              top: 57.0,
                              right: null,
                              bottom: null,
                              width: 235.0,
                              height: 27.0,
                              child: GeneratedForgotPasswordWidget1(),
                            ),
                          Positioned(
                                left: 20.0,
                                top: 50.0,
                                right: null,
                                bottom: null,
                                width: 40.0,
                                height: 40.0,
                                child: IconButton(
                                  icon: Icon(Icons.arrow_back),
                                  onPressed: (){
                                    Navigator.pop(context);
                                  },
                                ),
                              ),
                            Positioned(
                              left: 31.0,
                              top: 533.0,
                              right: null,
                              bottom: null,
                              width: 372.0,
                              height: 52.0,
                              child:
                                  GeneratedPleaseEnterYourPhoneNumberToRecieveaVerificationCodeWid(),
                            ),
                               Column(
                                 mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                      SizedBox(
                                        height: 480 ,

                                      ),
                                      Padding(padding: EdgeInsets.only(left: 20,right: 20),
                                        child: TextFormField(
                                          decoration: const InputDecoration(
                                            icon: Icon(Icons.phone),
                                            hintText: 'Phone Number',
                                          ),
                                        ),
                                      ),
                                      SizedBox(
                                        height: 70 ,
                                      ),
                                      Padding(
                                        padding: EdgeInsets.zero,
                                        child: Container(
                                          height: 60,
                                          width: 350,
                                          child: RaisedButton(
                                            onPressed: (){
                                              Navigator.push(
                                                context,
                                                MaterialPageRoute(builder: (context) => GeneratedCodephoneWidget()),
                                              );
                                            },
                                            color: AppColors.third,
                                            shape: RoundedRectangleBorder(
                                                borderRadius: BorderRadius.circular(30)),
                                            child: Text('Send Code',
                                            style: TextStyle(
                                              fontFamily: 'Montserrat',
                                              fontWeight: FontWeight.w700,
                                              fontSize: 25,
                                              color: Colors.white,
                                            ),),

                                          ),
                                        )
                                      ),
                                    ],
                            ),
                            Positioned(
                              left: 46.0,
                              top: 163.0,
                              right: null,
                              bottom: null,
                              width: 321.0,
                              height: 326.0,
                              child:
                                  GeneratedWavy_Tech28_Single10Converted11Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
