import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget3/generated/GeneratedRectangle2Widget15.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget3/generated/GeneratedRectangle13Widget2.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget3/generated/GeneratedEllipse42Widget1.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget3/generated/GeneratedUploadPhotoWidget4.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget3/generated/GeneratedOpenCameraWidget.dart';
import 'package:untitled5/helpers/transform/transform.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget3/generated/GeneratedVectorWidget809.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget3/generated/GeneratedVectorWidget808.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget3/generated/GeneratedSaveChangesWidget2.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget3/generated/GeneratedUploadfromGalleryWidget.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget3/generated/GeneratedVector25Widget20.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget3/generated/GeneratedRectangle15Widget4.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget3/generated/GeneratedUserUser_01Widget1.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget3/generated/GeneratedRectangle14Widget6.dart';

import '../../theme/themee.dart';

/* Frame Upload Photo
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUploadPhotoWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 930,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none, fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle2Widget15(),
                            ),
                            Positioned(
                              left: 330.0,
                              top: -118.0,
                              right: null,
                              bottom: null,
                              width: 239.564697265625,
                              height: 251.9700164794922,
                              child: GeneratedVectorWidget808(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 50.0,
                              right: null,
                              bottom: null,
                              width: 42.0,
                              height: 40.0,
                              child: IconButton(
                                onPressed: (){},
                                icon: Icon(Icons.arrow_back,size: 30,color: Colors.grey,),
                              ),
                            ),
                            Positioned(
                              left: 118.0,
                              top: 57.0,
                              right: null,
                              bottom: null,
                              width: 194.0,
                              height: 27.0,
                              child: GeneratedUploadPhotoWidget4(),
                            ),
                            Positioned(
                              left: 134.546875,
                              top: 1032.8741455078125,
                              right: null,
                              bottom: null,
                              width: 239.564697265625,
                              height: 251.9700164794922,
                              child: GeneratedVectorWidget809(),
                            ),
                            Positioned(
                              left: 41.0,
                              top: 691.0,
                              right: null,
                              bottom: null,
                              width: 347.0,
                              height: 44.0,
                              child: RaisedButton(onPressed: (){},
                                color: AppColors.third,
                                shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(30)),
                                child:
                                Text('Save Changes',style: TextStyle(
                                  fontSize: 18,
                                  fontWeight: FontWeight.w700,
                                  fontFamily: 'Montserrat',
                                  color: Colors.white,
                                ),),),
                            ),
                            Positioned(
                              left: 51.0,
                              top: 420.0,
                              right: null,
                              bottom: null,
                              width: 300.0,
                              height: 44.0,
                              child:  RaisedButton(onPressed: (){},
                                color: Colors.white,
                                shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(15)),
                                child:
                                Text('Open Camera',style: TextStyle(
                                  fontSize: 18,
                                  fontWeight: FontWeight.w700,
                                  fontFamily: 'Montserrat',
                                  color: AppColors.fifth,
                                ),),),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 506.0,
                              right: null,
                              bottom: null,
                              width: 370.0,
                              height: 44.0,
                              child:  RaisedButton(onPressed: (){},
                                color: Colors.white,
                                shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(15)),
                                child:
                                Text('Upload From Galery',style: TextStyle(
                                  fontSize: 18,
                                  fontWeight: FontWeight.w700,
                                  fontFamily: 'Montserrat',
                                  color: AppColors.fifth,
                                ),),),
                            ),

                            Positioned(
                              left: 124.0,
                              top: 183.0,
                              right: null,
                              bottom: null,
                              width: 173.0,
                              height: 173.0,
                              child: GeneratedUserUser_01Widget1(),
                            ),
                            Positioned(
                              left: 112.0,
                              top: 154.0,
                              right: null,
                              bottom: null,
                              width: 196.0,
                              height: 196.0,
                              child: GeneratedEllipse42Widget1(),
                            ),
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
