import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generatedaddcardwidget/generated/GeneratedAvatarBackgroundWidget7.dart';
import 'package:untitled5/helpers/transform/transform.dart';
import 'package:untitled5/untitledapp/generatedaddcardwidget/generated/GeneratedRectangle716Widget.dart';
import 'package:untitled5/untitledapp/generatedaddcardwidget/generated/GeneratedRectangle717Widget.dart';
import 'package:untitled5/untitledapp/generatedaddcardwidget/generated/GeneratedRectangle714Widget.dart';
import 'package:untitled5/untitledapp/generatedaddcardwidget/generated/GeneratedExpiresWidget.dart';
import 'package:untitled5/untitledapp/generatedaddcardwidget/generated/GeneratedADDWidget.dart';
import 'package:untitled5/untitledapp/generatedaddcardwidget/generated/GeneratedCartGradient2Widget.dart';
import 'package:untitled5/untitledapp/generatedaddcardwidget/generated/GeneratedRectangle8Widget11.dart';
import 'package:untitled5/untitledapp/generatedaddcardwidget/generated/GeneratedInterfaceShopping_Cart_01Widget6.dart';
import 'package:untitled5/untitledapp/generatedaddcardwidget/generated/GeneratedArrowCaret_Right_SMWidget14.dart';
import 'package:untitled5/untitledapp/generatedaddcardwidget/generated/GeneratedRectangle1Widget30.dart';
import 'package:untitled5/untitledapp/generatedaddcardwidget/generated/GeneratedCardNumberWidget.dart';
import 'package:untitled5/untitledapp/generatedaddcardwidget/generated/GeneratedDelivertoWidget6.dart';
import 'package:untitled5/untitledapp/generatedaddcardwidget/generated/GeneratedPaymentMethodWidget2.dart';
import 'package:untitled5/untitledapp/generatedaddcardwidget/generated/GeneratedVector25Widget16.dart';
import 'package:untitled5/untitledapp/generatedaddcardwidget/generated/GeneratedAvatarWidget7.dart';
import 'package:untitled5/untitledapp/generatedaddcardwidget/generated/GeneratedRectangle715Widget.dart';
import 'package:untitled5/untitledapp/generatedaddcardwidget/generated/GeneratedCardHolderWidget.dart';
import 'package:untitled5/untitledapp/generatedaddcardwidget/generated/GeneratedVectorWidget800.dart';
import 'package:untitled5/untitledapp/generatedaddcardwidget/generated/GeneratedA28SecondFloorSector64Noida20130102Widget11.dart';
import 'package:untitled5/untitledapp/generatedaddcardwidget/generated/GeneratedCVVWidget.dart';

import '../../theme/themee.dart';

/* Frame Add card
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAddcardWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none, fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle1Widget30(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 40.0,
                              right: null,
                              bottom: null,
                              width: 58.0,
                              height: 58.0,
                              child: GeneratedAvatarBackgroundWidget7(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 43.0,
                              right: null,
                              bottom: null,
                              width: 59.0,
                              height: 59.0,
                              child: GeneratedAvatarWidget7(),
                            ),
                            Positioned(
                              left: 172.0,
                              top: 47.0,
                              right: null,
                              bottom: null,
                              width: 87.0,
                              height: 17.0,
                              child: GeneratedDelivertoWidget6(),
                            ),
                            Positioned(
                              left: 109.0,
                              top: 66.0,
                              right: null,
                              bottom: null,
                              width: 212.0,
                              height: 30.0,
                              child:
                                  GeneratedA28SecondFloorSector64Noida20130102Widget11(),
                            ),
                            Positioned(
                              left: 278.9794921875,
                              top: 41.0,
                              right: null,
                              bottom: null,
                              width: 27.979501724243164,
                              height: 27.979501724243164,
                              child: GeneratedArrowCaret_Right_SMWidget14(),
                            ),
                            Positioned(
                              left: 328.0,
                              top: -116.0,
                              right: null,
                              bottom: null,
                              width: 239.564697265625,
                              height: 251.9700164794922,
                              child: GeneratedVectorWidget800(),
                            ),
                            Positioned(
                              left: 358.0,
                              top: 50.0,
                              right: null,
                              bottom: null,
                              width: 43.0,
                              height: 43.0,
                              child:
                                  GeneratedInterfaceShopping_Cart_01Widget6(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 137.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 0.0,
                              child: GeneratedVector25Widget16(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 512.0,
                              right: null,
                              bottom: null,
                              width: 175.0,
                              height: 25.0,
                              child: GeneratedCardNumberWidget(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 601.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 25.0,
                              child: GeneratedCardHolderWidget(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 705.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 28.0,
                              child: GeneratedExpiresWidget(),
                            ),
                            Positioned(
                              left: 219.0,
                              top: 705.0,
                              right: null,
                              bottom: null,
                              width: 55.0,
                              height: 28.0,
                              child: GeneratedCVVWidget(),
                            ),
                            Positioned(
                              left: 93.0,
                              top: 123.0,
                              right: null,
                              bottom: null,
                              width: 244.0,
                              height: 27.0,
                              child: GeneratedPaymentMethodWidget2(),
                            ),
                            Column(

                              children: [
                                SizedBox( height : 540),
                                Container(
                                  width: 380,
                                  height: 50,
                                  decoration: BoxDecoration(
                                    color: AppColors.seven,
                                    borderRadius: BorderRadius.circular(20),
                                  ),
                                  child: TextField(
                                    decoration: InputDecoration(
                                      border: OutlineInputBorder(
                                        borderRadius: BorderRadius.circular(20.0),
                                      ),
                                      fillColor: Colors.black12,
                                    ),
                                  ),
                                ),
                                SizedBox( height : 35),
                                Container(
                                  width: 380,
                                  height: 50,
                                  decoration: BoxDecoration(
                                    color: AppColors.seven,
                                    borderRadius: BorderRadius.circular(20),
                                  ),
                                  child: TextField(
                                    decoration: InputDecoration(
                                      border: OutlineInputBorder(
                                        borderRadius: BorderRadius.circular(20.0),
                                      ),
                                    ),
                                  ),
                                ), SizedBox( height : 55),
                                Row(
                                    children:[
                                      SizedBox(width: 20,),
                                      Container(
                                        width: 170,
                                        height: 50,
                                        decoration: BoxDecoration(
                                          color: AppColors.seven,
                                          borderRadius: BorderRadius.circular(20),
                                        ),
                                        child: TextField(
                                          decoration: InputDecoration(
                                            focusColor: Colors.black12,
                                            border: OutlineInputBorder(
                                              borderRadius: BorderRadius.circular(20.0),
                                            ),
                                          ),
                                        ),
                                      ),
                                      SizedBox(width: 30,),
                                      Container(
                                        width: 170,
                                        height: 50,
                                          decoration: BoxDecoration(
                                            color: AppColors.seven,
                                            borderRadius: BorderRadius.circular(20),
                                          ),
                                        child: TextField(
                                          decoration: InputDecoration(
                                            border: OutlineInputBorder(
                                              borderRadius: BorderRadius.circular(20.0),
                                            ),
                                          ),
                                        ),
                                      ),
                                    ]
                                ),
                                SizedBox(height: 70,),
                                Container(
                                  width: 200,
                                  height: 40,
                                  child : RaisedButton(
                                    onPressed: (){} ,
                                    color: AppColors.third,
                                    shape:RoundedRectangleBorder(
                                        borderRadius: BorderRadius.circular(30)),
                                    child : Center(
                                      child: Text('ADD',style: TextStyle(
                                        fontSize: 25,
                                        fontWeight: FontWeight.w700,
                                        fontFamily: 'Montserrat',
                                        color: Colors.white,
                                      ),),
                                    ),
                                  )
                                )
                              ],
                            ),
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
