import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/Generated4Widget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/Generated6Widget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/Generated8Widget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/Generated9Widget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedFrameWidget6.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedPleaseEnterThe4DigitCodeSentToYourEmailWidget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedRectangle10Widget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedRectangle11Widget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedRectangle12Widget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedRectangle1Widget12.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedRectangle8Widget4.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedRectangle9Widget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedResendCodeWidget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedVector25Widget6.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedVector34Widget1.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedVector35Widget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedVector36Widget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedVector37Widget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedVector38Widget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedVerifyWidget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedVerifyYourEmailWidget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedWavy_Gen03_Single06Converted1Widget.dart';
import 'package:untitled5/untitledapp/generatednewpasswordwidget/GeneratedNewPasswordWidget.dart';

import '../../helpers/transform/transform.dart';
import '../../theme/themee.dart';

/* Frame Code email
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCodeemailWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none, fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 428.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle1Widget12(),
                            ),
                            Positioned(
                              left: 92.0,
                              top: 57.0,
                              right: null,
                              bottom: null,
                              width: 246.0,
                              height: 27.0,
                              child: GeneratedVerifyYourEmailWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 50.0,
                              right: null,
                              bottom: null,
                              width: 42.0,
                              height: 42.0,
                              child: IconButton
                                (icon : Icon(Icons.arrow_back), onPressed: () { Navigator.pop(context); },),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 505.0,
                              right: null,
                              bottom: null,
                              width: 372.0,
                              height: 58.0,
                              child:
                                  GeneratedPleaseEnterThe4DigitCodeSentToYourEmailWidget(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 135.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 342.0,
                              child:
                                  GeneratedWavy_Gen03_Single06Converted1Widget(),
                            ),
                            Column(
                              mainAxisAlignment: MainAxisAlignment.center,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              children: [
                                SizedBox(
                                  height: 480 ,

                                ),
                                Padding(
                                  padding: EdgeInsets.only(right: 50,left: 50),
                                  child: Row(
                                    mainAxisAlignment: MainAxisAlignment.spaceAround,
                                    children: [
                                      Container(
                                        height : 50,
                                        width: 50,
                                        decoration: BoxDecoration(
                                          color: Colors.black12,
                                          borderRadius: BorderRadius.circular(15),
                                        ),
                                        child: TextFormField(
                                          textAlign: TextAlign.center,
                                        ),
                                      ),
                                      Container(
                                        height : 50,
                                        width: 50,
                                        decoration: BoxDecoration(
                                          color: Colors.black12,
                                          borderRadius: BorderRadius.circular(15),
                                        ),
                                        child: TextFormField(
                                          textAlign: TextAlign.center,
                                        ),
                                      ),
                                      Container(
                                        height : 50,
                                        width: 50,
                                        decoration: BoxDecoration(
                                          color: Colors.black12,
                                          borderRadius: BorderRadius.circular(15),
                                        ),
                                        child: TextFormField(
                                          textAlign: TextAlign.center,
                                        ),
                                      ),
                                      Container(
                                        height : 50,
                                        width: 50,
                                        decoration: BoxDecoration(
                                          color: Colors.black12,
                                          borderRadius: BorderRadius.circular(15),
                                        ),
                                        child: TextFormField(
                                          textAlign: TextAlign.center,
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                                SizedBox(
                                  height: 70 ,
                                ),
                                InkWell(onTap: (){},
                                  child: Text('Resend Code',
                                    style: TextStyle(
                                      fontFamily: 'Montserrat',
                                      fontWeight: FontWeight.w700,
                                      fontSize: 12,
                                      color: AppColors.fifth,
                                    ),),
                                ),
                                Divider(
                                    height: 15,
                                    thickness: 4,
                                    indent: 140,
                                    endIndent: 140,
                                    color: AppColors.third
                                ),
                                SizedBox(
                                  height: 20 ,
                                ),

                                Padding(
                                    padding: EdgeInsets.zero,
                                    child: Container(
                                      height: 60,
                                      width: 350,
                                      child: RaisedButton(
                                        onPressed: (){
                                          Navigator.push(
                                            context,
                                            MaterialPageRoute(builder: (context) => GeneratedNewPasswordWidget()),
                                          );
                                        },
                                        color: AppColors.third,
                                        shape: RoundedRectangleBorder(
                                            borderRadius: BorderRadius.circular(30)),
                                        child: Text('Verify',
                                          style: TextStyle(
                                            fontFamily: 'Montserrat',
                                            fontWeight: FontWeight.w700,
                                            fontSize: 25,
                                            color: Colors.white,
                                          ),),

                                      ),
                                    )
                                ),
                              ],
                            ),
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
