import 'package:flutter/material.dart';
import 'package:untitled5/helpers/transform/transform.dart';
import 'package:untitled5/untitledapp/generatedinfowidget1/generated/GeneratedRectangle13Widget3.dart';
import 'package:untitled5/untitledapp/generatedinfowidget1/generated/GeneratedVectorWidget829.dart';
import 'package:untitled5/untitledapp/generatedinfowidget1/generated/GeneratedAvatarWidget19.dart';
import 'package:untitled5/untitledapp/generatedinfowidget1/generated/GeneratedRectangle8Widget13.dart';
import 'package:untitled5/untitledapp/generatedinfowidget1/generated/GeneratedEnteraValidPromocodeWidget.dart';
import 'package:untitled5/untitledapp/generatedinfowidget1/generated/GeneratedInterfaceTicket_VoucherWidget3.dart';
import 'package:untitled5/untitledapp/generatedinfowidget1/generated/GeneratedUserID184B756Widget3.dart';
import 'package:untitled5/untitledapp/generatedinfowidget1/generated/GeneratedVectorWidget827.dart';
import 'package:untitled5/untitledapp/generatedinfowidget1/generated/GeneratedEditEdit_Pencil_01Widget6.dart';
import 'package:untitled5/untitledapp/generatedinfowidget1/generated/GeneratedAvatarBackgroundWidget19.dart';
import 'package:untitled5/untitledapp/generatedinfowidget1/generated/GeneratedInterfaceTicket_VoucherWidget2.dart';
import 'package:untitled5/untitledapp/generatedinfowidget1/generated/GeneratedApplyWidget2.dart';
import 'package:untitled5/untitledapp/generatedinfowidget1/generated/GeneratedUserNamegmailcomWidget3.dart';
import 'package:untitled5/untitledapp/generatedinfowidget1/generated/GeneratedMyProfileWidget3.dart';
import 'package:untitled5/untitledapp/generatedinfowidget1/generated/GeneratedRectangle2Widget17.dart';
import 'package:untitled5/untitledapp/generatedinfowidget1/generated/GeneratedVector25Widget22.dart';
import 'package:untitled5/untitledapp/generatedinfowidget1/generated/GeneratedRectangle7Widget8.dart';
import 'package:untitled5/untitledapp/generatedinfowidget1/generated/GeneratedUserNameWidget3.dart';
import 'package:untitled5/untitledapp/generatedinfowidget1/generated/GeneratedVector39Widget.dart';
import 'package:untitled5/untitledapp/generatedinfowidget1/generated/GeneratedPromocodesWidget2.dart';

/* Frame Info
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInfoWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1284.8441619873047,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none, fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle2Widget17(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -51.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 347.0,
                              child: GeneratedRectangle7Widget8(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 425.0,
                              right: null,
                              bottom: null,
                              width: 387.0,
                              height: 325.0,
                              child: GeneratedRectangle8Widget13(),
                            ),
                            Positioned(
                              left: 104.0,
                              top: 693.0,
                              right: null,
                              bottom: null,
                              width: 221.0,
                              height: 40.0,
                              child: GeneratedRectangle13Widget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.633177570093458;

                                final double height = constraints.maxHeight *
                                    0.029157667386609073;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.18925233644859812,
                                      y: constraints.maxHeight *
                                          0.7570194384449244,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedApplyWidget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 32.0,
                              top: 490.0,
                              right: null,
                              bottom: null,
                              width: 351.0003662109375,
                              height: 0.0,
                              child: GeneratedVector39Widget(),
                            ),
                            Positioned(
                              left: 311.0,
                              top: -107.0,
                              right: null,
                              bottom: null,
                              width: 239.564697265625,
                              height: 251.9700164794922,
                              child: GeneratedVectorWidget827(),
                            ),
                            Positioned(
                              left: 372.0,
                              top: 53.0,
                              right: null,
                              bottom: null,
                              width: 34.0,
                              height: 34.0,
                              child: GeneratedEditEdit_Pencil_01Widget6(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 70.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 0.0,
                              child: GeneratedVector25Widget22(),
                            ),
                            Positioned(
                              left: 145.0,
                              top: 57.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 27.0,
                              child: GeneratedMyProfileWidget3(),
                            ),
                            Positioned(
                              left: 145.0,
                              top: 151.0,
                              right: null,
                              bottom: null,
                              width: 144.0,
                              height: 25.0,
                              child: GeneratedUserNameWidget3(),
                            ),
                            Positioned(
                              left: 145.0,
                              top: 191.0,
                              right: null,
                              bottom: null,
                              width: 206.0,
                              height: 21.0,
                              child: GeneratedUserNamegmailcomWidget3(),
                            ),
                            Positioned(
                              left: 145.0,
                              top: 223.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 18.0,
                              child: GeneratedUserID184B756Widget3(),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 140.0,
                              right: null,
                              bottom: null,
                              width: 104.0,
                              height: 104.0,
                              child: GeneratedAvatarBackgroundWidget19(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 149.0,
                              right: null,
                              bottom: null,
                              width: 103.0,
                              height: 101.0,
                              child: GeneratedAvatarWidget19(),
                            ),
                            Positioned(
                              left: 134.546875,
                              top: 1032.8741455078125,
                              right: null,
                              bottom: null,
                              width: 239.564697265625,
                              height: 251.9700164794922,
                              child: GeneratedVectorWidget829(),
                            ),
                            Positioned(
                              left: 87.0,
                              top: 461.0,
                              right: null,
                              bottom: null,
                              width: 242.0,
                              height: 19.0,
                              child: GeneratedEnteraValidPromocodeWidget(),
                            ),
                            Positioned(
                              left: 164.0,
                              top: 346.0,
                              right: null,
                              bottom: null,
                              width: 161.0,
                              height: 28.0,
                              child: GeneratedPromocodesWidget2(),
                            ),
                            Positioned(
                              left: 108.0,
                              top: 338.0,
                              right: null,
                              bottom: null,
                              width: 38.0,
                              height: 38.0,
                              child: GeneratedInterfaceTicket_VoucherWidget2(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 450.0,
                              right: null,
                              bottom: null,
                              width: 38.0,
                              height: 38.0,
                              child: GeneratedInterfaceTicket_VoucherWidget3(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
