import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/Generated4Widget1.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/Generated6Widget1.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/Generated8Widget1.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/Generated9Widget1.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedFrameWidget7.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedPleaseEnterThe4DigitCodeSentToYourPhoneNumberWidget.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedRectangle10Widget1.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedRectangle11Widget1.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedRectangle12Widget1.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedRectangle1Widget13.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedRectangle8Widget5.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedRectangle9Widget1.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedResendCodeWidget1.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedVector25Widget7.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedVector34Widget2.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedVector35Widget1.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedVector36Widget1.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedVector37Widget1.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedVerifyYourPhoneNumberWidget.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedWavy_Gen01_Single02Converted1Widget.dart';

import '../../helpers/transform/transform.dart';
import '../../theme/themee.dart';
import '../generatednewpasswordwidget/GeneratedNewPasswordWidget.dart';
import 'generated/GeneratedVerifyWidget1.dart';

/* Frame Code phone
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCodephoneWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none, fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 428.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle1Widget13(),
                            ),
                            Positioned(
                              left: 93.0,
                              top: 57.0,
                              right: null,
                              bottom: null,
                              width: 268.0,
                              height: 58.0,
                              child: GeneratedVerifyYourPhoneNumberWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 50.0,
                              right: null,
                              bottom: null,
                              width: 42.0,
                              height: 42.0,
                              child: InkWell(onTap: (){
                                Navigator.pop(context);
                              },child: Icon(Icons.arrow_back),),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 506.0,
                              right: null,
                              bottom: null,
                              width: 372.0,
                              height: 58.0,
                              child:
                                  GeneratedPleaseEnterThe4DigitCodeSentToYourPhoneNumberWidget(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 143.0,
                              right: null,
                              bottom: null,
                              width: 336.0,
                              height: 334.0,
                              child:
                                  GeneratedWavy_Gen01_Single02Converted1Widget(),
                            ),
                            Column(
                              mainAxisAlignment: MainAxisAlignment.center,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              children: [
                                  SizedBox(
                                    height: 480 ,

                                  ),
                                  Padding(
                                    padding: EdgeInsets.only(right: 50,left: 50),
                                    child: Row(
                                      mainAxisAlignment: MainAxisAlignment.spaceAround,
                                      children: [
                                        Container(
                                          height : 50,
                                          width: 50,
                                          decoration: BoxDecoration(
                                            color: Colors.black12,
                                            borderRadius: BorderRadius.circular(15),
                                          ),
                                          child: TextFormField(
                                            textAlign: TextAlign.center,
                                          ),
                                        ),
                                        Container(
                                          height : 50,
                                          width: 50,
                                          decoration: BoxDecoration(
                                            color: Colors.black12,
                                            borderRadius: BorderRadius.circular(15),
                                          ),
                                          child: TextFormField(
                                            textAlign: TextAlign.center,
                                            ),
                                          ),
                                        Container(
                                          height : 50,
                                          width: 50,
                                          decoration: BoxDecoration(
                                            color: Colors.black12,
                                            borderRadius: BorderRadius.circular(15),
                                          ),
                                          child: TextFormField(
                                            textAlign: TextAlign.center,
                                          ),
                                        ),
                                        Container(
                                          height : 50,
                                          width: 50,
                                          decoration: BoxDecoration(
                                            color: Colors.black12,
                                            borderRadius: BorderRadius.circular(15),
                                          ),
                                          child: TextFormField(
                                            textAlign: TextAlign.center,
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                  SizedBox(
                                    height: 70 ,
                                  ),
                                InkWell(onTap: (){},
                                  child: Text('Resend Code',
                                    style: TextStyle(
                                      fontFamily: 'Montserrat',
                                      fontWeight: FontWeight.w700,
                                      fontSize: 12,
                                      color: AppColors.fifth,
                                    ),),
                                ),
                                Divider(
                                    height: 15,
                                    thickness: 4,
                                    indent: 140,
                                    endIndent: 140,
                                    color: AppColors.third
                                ),
                                SizedBox(
                                  height: 20 ,
                                ),

                                Padding(
                                      padding: EdgeInsets.zero,
                                      child: Container(
                                        height: 60,
                                        width: 350,
                                        child: RaisedButton(
                                          onPressed: (){
                                            Navigator.push(
                                              context,
                                              MaterialPageRoute(builder: (context) => GeneratedNewPasswordWidget()),
                                            );
                                          },
                                          color: AppColors.third,
                                          shape: RoundedRectangleBorder(
                                              borderRadius: BorderRadius.circular(30)),
                                          child: Text('Verify',
                                            style: TextStyle(
                                              fontFamily: 'Montserrat',
                                              fontWeight: FontWeight.w700,
                                              fontSize: 25,
                                              color: Colors.white,
                                            ),),

                                        ),
                                      )
                                  ),
                              ],
                            ),
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
