import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generatedemptywidget/generated/GeneratedVector25Widget15.dart';
import 'package:untitled5/untitledapp/generatedemptywidget/generated/GeneratedWavy_Bus26_Single01Converted1Widget1.dart';
import 'package:untitled5/untitledapp/generatedemptywidget/generated/GeneratedRectangle16Widget3.dart';
import 'package:untitled5/untitledapp/generatedemptywidget/generated/GeneratedRectangle15Widget3.dart';
import 'package:untitled5/untitledapp/generatedemptywidget/generated/GeneratedMyOrdersWidget4.dart';
import 'package:untitled5/untitledapp/generatedemptywidget/generated/GeneratedVectorWidget794.dart';
import 'package:untitled5/untitledapp/generatedemptywidget/generated/GeneratedHistoryWidget3.dart';
import 'package:untitled5/untitledapp/generatedemptywidget/generated/GeneratedUpcomingWidget3.dart';
import 'package:untitled5/untitledapp/generatedemptywidget/generated/GeneratedItAppearsthatyourorderslistisemptyWidget1.dart';
import 'package:untitled5/untitledapp/generatedemptywidget/generated/GeneratedRectangle2Widget10.dart';
import 'package:untitled5/untitledapp/generatedemptywidget/generated/GeneratedVectorWidget793.dart';

/* Frame Empty
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEmptyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 930.8441619873047,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none, fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle2Widget10(),
                            ),
                            Positioned(
                              left: 311.0,
                              top: -107.0,
                              right: null,
                              bottom: null,
                              width: 239.564697265625,
                              height: 251.9700164794922,
                              child: GeneratedVectorWidget793(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 70.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 0.0,
                              child: GeneratedVector25Widget15(),
                            ),
                            Positioned(
                              left: 150.0,
                              top: 58.0,
                              right: null,
                              bottom: null,
                              width: 130.0,
                              height: 25.0,
                              child: GeneratedMyOrdersWidget4(),
                            ),
                            Positioned(
                              left: 134.546875,
                              top: 1058.8741455078125,
                              right: null,
                              bottom: null,
                              width: 239.564697265625,
                              height: 251.9700164794922,
                              child: GeneratedVectorWidget794(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 156.0,
                              right: null,
                              bottom: null,
                              width: 366.0,
                              height: 62.0,
                              child: GeneratedRectangle15Widget3(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 161.0,
                              right: null,
                              bottom: null,
                              width: 176.0,
                              height: 53.0,
                              child: InkWell(onTap : () {} ,child: GeneratedRectangle16Widget3()),
                            ),
                            Positioned(
                              left: 58.0,
                              top: 176.0,
                              right: null,
                              bottom: null,
                              width: 138.0,
                              height: 28.0,
                              child: InkWell(onTap : () {} ,child: GeneratedUpcomingWidget3()),
                            ),
                            Positioned(
                              left: 261.0,
                              top: 176.0,
                              right: null,
                              bottom: null,
                              width: 99.0,
                              height: 28.0,
                              child: Container( width : 100 , height : 50 , child: InkWell( onTap : (){} , child: GeneratedHistoryWidget3())),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 390.0,
                              right: null,
                              bottom: null,
                              width: 365.0,
                              height: 373.0,
                              child:
                                  GeneratedWavy_Bus26_Single01Converted1Widget1(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 264.0,
                              right: null,
                              bottom: null,
                              width: 371.0,
                              height: 74.0,
                              child:
                                  GeneratedItAppearsthatyourorderslistisemptyWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
