import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/GeneratedINTROWidget.dart';
import 'package:untitled5/untitledapp/generatedsigninwidget/GeneratedSigninWidget.dart';
import 'package:untitled5/untitledapp/generatedsplashscreenwidget/generated/GeneratedImage1Widget.dart';
import 'package:untitled5/untitledapp/generatedsplashscreenwidget/generated/GeneratedRectangle1Widget.dart';
import 'package:untitled5/untitledapp/generatedsplashscreenwidget/generated/GeneratedVector3Widget.dart';
import 'package:untitled5/untitledapp/generatedsplashscreenwidget/generated/GeneratedVector4Widget.dart';
import 'package:untitled5/untitledapp/generatedsplashscreenwidget/generated/GeneratedVector5Widget.dart';
import 'package:untitled5/untitledapp/generatedsplashscreenwidget/generated/GeneratedVector6Widget.dart';
import 'package:untitled5/theme/themee.dart';
import 'package:easy_splash_screen/easy_splash_screen.dart';

/* Frame Splash Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplashScreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
       return EasySplashScreen(
         logoSize: 100,
        logo: Image.asset(
            'assets/images/aa.png',
        ),
        title: Text(
          "R E S T A U R A N T   P L A T E F O R M",
          style: TextStyle(
            fontSize: 16,
            fontWeight: FontWeight.bold,
            fontFamily: 'Montserrat',
            color: Colors.white,
          ),
        ),
        backgroundColor: AppColors.third,
        showLoader: false,
        durationInSeconds:9,
        navigator: GeneratedINTROWidget(),
     );
  }

}