import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generatedfeedbackwidget/generated/GeneratedVector42Widget6.dart';
import 'package:untitled5/untitledapp/generatedfeedbackwidget/generated/GeneratedYourexperiencewithyourcourrierNameSurnameWidget.dart';
import 'package:untitled5/untitledapp/generatedfeedbackwidget/generated/GeneratedStar10Widget2.dart';
import 'package:untitled5/untitledapp/generatedfeedbackwidget/generated/GeneratedRectangle706Widget5.dart';
import 'package:untitled5/untitledapp/generatedfeedbackwidget/generated/GeneratedGiveusFeedbackWidget1.dart';
import 'package:untitled5/untitledapp/generatedfeedbackwidget/generated/GeneratedThankYouWidget.dart';
import 'package:untitled5/untitledapp/generatedfeedbackwidget/generated/GeneratedStar14Widget.dart';
import 'package:untitled5/untitledapp/generatedfeedbackwidget/generated/GeneratedStar11Widget1.dart';
import 'package:untitled5/untitledapp/generatedfeedbackwidget/generated/GeneratedRectangle713Widget1.dart';
import 'package:untitled5/untitledapp/generatedfeedbackwidget/generated/GeneratedAvatarWidget23.dart';
import 'package:untitled5/untitledapp/generatedfeedbackwidget/generated/GeneratedSUBMITWidget1.dart';
import 'package:untitled5/untitledapp/generatedfeedbackwidget/generated/GeneratedAvatarBackgroundWidget27.dart';
import 'package:untitled5/untitledapp/generatedfeedbackwidget/generated/GeneratedYourexperiencewithusingtheappWidget.dart';
import 'package:untitled5/untitledapp/generatedfeedbackwidget/generated/GeneratedRectangle1Widget46.dart';
import 'package:untitled5/untitledapp/generatedfeedbackwidget/generated/GeneratedVectorWidget889.dart';
import 'package:untitled5/untitledapp/generatedfeedbackwidget/generated/GeneratedStar7Widget2.dart';
import 'package:untitled5/untitledapp/generatedfeedbackwidget/generated/GeneratedRectangle8Widget22.dart';
import 'package:untitled5/untitledapp/generatedfeedbackwidget/generated/GeneratedSkipWidget.dart';
import 'package:untitled5/untitledapp/generatedfeedbackwidget/generated/GeneratedStar13Widget.dart';
import 'package:untitled5/untitledapp/generatedfeedbackwidget/generated/GeneratedRectangle714Widget2.dart';
import 'package:untitled5/untitledapp/generatedfeedbackwidget/generated/GeneratedGiveusFeedbackWidget.dart';
import 'package:untitled5/untitledapp/generatedfeedbackwidget/generated/GeneratedYourfoodorderhasbeendeliveredWidget.dart';
import 'package:untitled5/untitledapp/generatedfeedbackwidget/generated/GeneratedStar12Widget.dart';
import 'package:untitled5/helpers/transform/transform.dart';
import 'package:untitled5/untitledapp/generatedfeedbackwidget/generated/GeneratedStar9Widget2.dart';
import 'package:untitled5/untitledapp/generatedfeedbackwidget/generated/GeneratedStar8Widget2.dart';
import 'package:untitled5/untitledapp/generatedfeedbackwidget/generated/GeneratedStar16Widget.dart';
import 'package:untitled5/untitledapp/generatedfeedbackwidget/generated/GeneratedStar15Widget.dart';

/* Frame Feedback
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFeedbackWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none, fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle1Widget46(),
                            ),
                            Positioned(
                              left: -1.0,
                              top: -12.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 263.0,
                              child: GeneratedRectangle706Widget5(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 40.0,
                              right: null,
                              bottom: null,
                              width: 58.0,
                              height: 58.0,
                              child: GeneratedAvatarBackgroundWidget27(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 43.0,
                              right: null,
                              bottom: null,
                              width: 59.0,
                              height: 59.0,
                              child: GeneratedAvatarWidget23(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 142.0,
                              right: null,
                              bottom: null,
                              width: 237.0,
                              height: 39.0,
                              child: GeneratedThankYouWidget(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 196.0,
                              right: null,
                              bottom: null,
                              width: 349.0,
                              height: 19.0,
                              child:
                                  GeneratedYourfoodorderhasbeendeliveredWidget(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 549.0,
                              right: null,
                              bottom: null,
                              width: 369.5,
                              height: 0.0,
                              child: GeneratedVector42Widget6(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.883177570093458;

                                final double height =
                                    constraints.maxHeight * 0.07991360691144708;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06775700934579439,
                                      y: constraints.maxHeight *
                                          0.30885529157667385,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedYourexperiencewithyourcourrierNameSurnameWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.883177570093458;

                                final double height =
                                    constraints.maxHeight * 0.07991360691144708;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06775700934579439,
                                      y: constraints.maxHeight *
                                          0.6198704103671706,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedYourexperiencewithusingtheappWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 269.41259765625,
                              top: -107.642578125,
                              right: null,
                              bottom: null,
                              width: 239.564697265625,
                              height: 251.9700164794922,
                              child: GeneratedVectorWidget889(),
                            ),
                            Column(
                              children: [
                                SizedBox(height: 400,),
                                Container(
                                  height: 200,
                                  width: 380,
                                  decoration: BoxDecoration(
                                    color: Colors.white,
                                  ),
                                  child:
                                      Column(
                                        children: [
                                          TextField(

                                          ),
                                        ],
                                      )
                                )
                              ],
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
