import 'package:flutter/material.dart';
import 'package:untitled5/theme/themee.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/GeneratedCodeemailWidget.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/GeneratedCodephoneWidget.dart';
import 'package:untitled5/untitledapp/generatedsendemailwidget/generated/GeneratedEMAILWidget.dart';
import 'package:untitled5/untitledapp/generatedsendemailwidget/generated/GeneratedForgotPasswordWidget.dart';
import 'package:untitled5/untitledapp/generatedsendemailwidget/generated/GeneratedFrameWidget4.dart';
import 'package:untitled5/untitledapp/generatedsendemailwidget/generated/GeneratedPleaseEnterYourEmailAddressToRecieveaVerificationCodeWi.dart';
import 'package:untitled5/untitledapp/generatedsendemailwidget/generated/GeneratedRectangle1Widget10.dart';
import 'package:untitled5/untitledapp/generatedsendemailwidget/generated/GeneratedRectangle8Widget2.dart';
import 'package:untitled5/untitledapp/generatedsendemailwidget/generated/GeneratedSendCodeWidget.dart';
import 'package:untitled5/untitledapp/generatedsendemailwidget/generated/GeneratedTryAnotherMethodWidget.dart';
import 'package:untitled5/untitledapp/generatedsendemailwidget/generated/GeneratedVector25Widget4.dart';
import 'package:untitled5/untitledapp/generatedsendemailwidget/generated/GeneratedVector34Widget.dart';
import 'package:untitled5/untitledapp/generatedsendemailwidget/generated/GeneratedWavy_Tech28_Single10Converted11Widget.dart';
import 'package:untitled5/untitledapp/generatedsendemailwidget/generated/GeneratedWavy_Tech28_Single10Converted1Widget.dart';
import 'package:untitled5/untitledapp/generatedsendphonewidget/GeneratedSendphoneWidget.dart';

import '../../helpers/transform/transform.dart';
import 'generated/GeneratedMailWidget.dart';
import 'generated/GeneratedVector26Widget.dart';

/* Frame Send email
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSendemailWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none, fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 428.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle1Widget10(),
                            ),
                            Positioned(
                              left: 98.0,
                              top: 57.0,
                              right: null,
                              bottom: null,
                              width: 235.0,
                              height: 27.0,
                              child: GeneratedForgotPasswordWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 50.0,
                              right: null,
                              bottom: null,
                              width: 42.0,
                              height: 42.0,
                              child: IconButton(
                                onPressed: (){
                                  Navigator.pop(context);
                                },
                                icon: Icon(Icons.arrow_back),
                              ),
                            ),
                            Positioned(
                              left: 33.0,
                              top: 533.0,
                              right: null,
                              bottom: null,
                              width: 364.0,
                              height: 52.0,
                              child:
                                  GeneratedPleaseEnterYourEmailAddressToRecieveaVerificationCodeWi(),
                            ),

                            Positioned(
                              left: 46.0,
                              top: 171.0,
                              right: null,
                              bottom: null,
                              width: 315.0,
                              height: 321.0,
                              child:
                                  GeneratedWavy_Tech28_Single10Converted1Widget(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 163.0,
                              right: null,
                              bottom: null,
                              width: 321.0,
                              height: 326.0,
                              child:
                                  GeneratedWavy_Tech28_Single10Converted11Widget(),
                            ),
                            Column(
                              mainAxisAlignment: MainAxisAlignment.center,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              children: [
                                SizedBox(
                                  height: 550,
                                ),
                                Padding(padding: EdgeInsets.only(left: 40,right: 40),
                                  child: TextFormField(
                                    decoration: const InputDecoration(
                                      icon: Icon(Icons.email_outlined),
                                      hintText: 'E-mail',
                                    ),
                                  ),
                                ),
                                SizedBox(
                                  height: 60,
                                ),
                                InkWell(onTap: (){
                                  Navigator.push(
                                    context,
                                    MaterialPageRoute(builder: (context) => GeneratedSendphoneWidget()),
                                  );
                                },
                                child: Text('Try Another Method',
                                style: TextStyle(
                                  fontFamily: 'Montserrat',
                                  fontWeight: FontWeight.w700,
                                  fontSize: 12,
                                  color: AppColors.fifth,
                                ),),
                                ),
                                Divider(
                                  height: 15,
                                  thickness: 4,
                                  indent: 140,
                                  endIndent: 140,
                                  color: AppColors.third
                                ),
                              SizedBox(height: 40,),
                              Padding(
                                padding: EdgeInsets.only(right: 20,left: 20),
                                child:
                                Container(
                                  height: 60,
                                  width: 350,
                                  child: RaisedButton(
                                    onPressed: (){
                                      Navigator.push(
                                        context,
                                        MaterialPageRoute(builder: (context) => GeneratedCodeemailWidget()),
                                      );
                                    },
                                    color: AppColors.third,
                                    shape: RoundedRectangleBorder(
                                        borderRadius: BorderRadius.circular(30)),
                                    child: Text('Send Code',
                                      style: TextStyle(
                                        fontFamily: 'Montserrat',
                                        fontWeight: FontWeight.w700,
                                        fontSize: 25,
                                        color: Colors.white,
                                      ),),
                                  ),
                                ),
                              ),
                              ],
                            ),
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
