import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget1/generated/GeneratedVectorWidget805.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget1/generated/GeneratedAvatarWidget17.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget1/generated/GeneratedUserUser_01Widget.dart';
import 'package:untitled5/helpers/transform/transform.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget1/generated/GeneratedAvatarWidget16.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget1/generated/GeneratedSaveChangesWidget1.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget1/generated/GeneratedEllipse42Widget.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget1/generated/GeneratedAvatarBackgroundWidget17.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget1/generated/GeneratedVectorWidget806.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget1/generated/GeneratedRectangle13Widget1.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget1/generated/GeneratedVector25Widget19.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget1/generated/GeneratedAvatarBackgroundWidget16.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget1/generated/GeneratedRectangle14Widget5.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget1/generated/GeneratedOrChooseanAvatarWidget.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget1/generated/GeneratedUploadPhotoWidget2.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget1/generated/GeneratedRectangle2Widget14.dart';
import 'package:untitled5/untitledapp/generateduploadphotowidget1/generated/GeneratedUploadYourPhotoWidget.dart';

import '../../theme/themee.dart';
import '../generatedaccountwidget/generated/GeneratedAvatarBackgroundWidget12.dart';
import '../generatededitprofilewidget/generated/GeneratedAvatarBackgroundWidget15.dart';

/* Frame Upload Photo
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUploadPhotoWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 930,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none, fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle2Widget14(),
                            ),
                            Positioned(
                              left: 330.0,
                              top: -118.0,
                              right: null,
                              bottom: null,
                              width: 239.564697265625,
                              height: 251.9700164794922,
                              child: GeneratedVectorWidget805(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 50.0,
                              right: null,
                              bottom: null,
                              width: 42.0,
                              height: 40.0,
                              child: IconButton(
                                onPressed: (){},
                                icon: Icon(Icons.arrow_back,size: 30,color: Colors.grey,),
                              ),
                            ),

                            Positioned(
                              left: 28.0,
                              top: 393.0,
                              right: null,
                              bottom: null,
                              width: 340.0,
                              height: 52.0,
                              child: RaisedButton(onPressed: (){},
                                color: Colors.white,
                                shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(30)),
                                child:
                                Text('Upload Your Photo',style: TextStyle(
                                  fontSize: 18,
                                  fontWeight: FontWeight.w700,
                                  fontFamily: 'Montserrat',
                                  color: AppColors.fifth,
                                ),),),
                            ),

                            Positioned(
                              left: 69.0,
                              top: 480.0,
                              right: null,
                              bottom: null,
                              width: 292.0,
                              height: 27.0,
                              child: GeneratedOrChooseanAvatarWidget(),
                            ),
                            Positioned(
                              left: 134.546875,
                              top: 1032.8741455078125,
                              right: null,
                              bottom: null,
                              width: 239.564697265625,
                              height: 251.9700164794922,
                              child: GeneratedVectorWidget806(),
                            ),
                            Positioned(
                              left: 41.0,
                              top: 691.0,
                              right: null,
                              bottom: null,
                              width: 340.0,
                              height: 44.0,
                              child: RaisedButton(onPressed: (){},
                                color: AppColors.third,
                                shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(30)),
                                child:
                                Text('Save Changes',style: TextStyle(
                                  fontSize: 18,
                                  fontWeight: FontWeight.w700,
                                  fontFamily: 'Montserrat',
                                  color: Colors.white,
                                ),),),
                            ),
                            Positioned(
                              left: 124.0,
                              top: 183.0,
                              right: null,
                              bottom: null,
                              width: 173.0,
                              height: 173.0,
                              child: GeneratedUserUser_01Widget(),
                            ),
                            Positioned(
                              left: 112.0,
                              top: 154.0,
                              right: null,
                              bottom: null,
                              width: 196.0,
                              height: 196.0,
                              child: GeneratedEllipse42Widget(),
                            ),
                            Column(
                              children: [
                                SizedBox(height: 550,),
                                Row(
                                  children: [
                                    SizedBox(width: 100,),
                                    InkWell(
                                      child:GeneratedAvatarBackgroundWidget12(),
                                    ),
                                    SizedBox(width: 16,),
                                    InkWell(
                                      child:GeneratedAvatarBackgroundWidget12(),
                                    ),
                                  ],
                                ),
                              ],
                            ) ,
                            Positioned(
                              left: 99.0,
                              top: 557.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 100.0,
                              child: InkWell(onTap: (){} , child: GeneratedAvatarWidget16()),
                            ),
                            Positioned(
                              left: 220.0,
                              top: 559.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 100.0,
                              child: InkWell(onTap:(){},child: GeneratedAvatarWidget17()),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
