import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generatededitprofilewidget/generated/GeneratedVectorWidget803.dart';
import 'package:untitled5/untitledapp/generatededitprofilewidget/generated/GeneratedRectangle13Widget.dart';
import 'package:untitled5/untitledapp/generatededitprofilewidget/generated/GeneratedSaveChangesWidget.dart';
import 'package:untitled5/untitledapp/generatededitprofilewidget/generated/GeneratedRectangle8Widget12.dart';
import 'package:untitled5/untitledapp/generatededitprofilewidget/generated/GeneratedRectangle9Widget6.dart';
import 'package:untitled5/untitledapp/generatededitprofilewidget/generated/GeneratedVector40Widget.dart';
import 'package:untitled5/untitledapp/generatededitprofilewidget/generated/GeneratedFileFolder_UploadWidget.dart';
import 'package:untitled5/untitledapp/generatededitprofilewidget/generated/GeneratedRectangle2Widget13.dart';
import 'package:untitled5/untitledapp/generatededitprofilewidget/generated/GeneratedChangePhoneNumber21699999999Widget.dart';
import 'package:untitled5/untitledapp/generatededitprofilewidget/generated/GeneratedRectangle10Widget4.dart';
import 'package:untitled5/untitledapp/generatededitprofilewidget/generated/GeneratedUploadPhotoWidget.dart';
import 'package:untitled5/untitledapp/generatededitprofilewidget/generated/GeneratedChangeEmailAddressUsernamegmailcomWidget.dart';
import 'package:untitled5/helpers/transform/transform.dart';
import 'package:untitled5/untitledapp/generatededitprofilewidget/generated/GeneratedChangeDeliveryAddresTunisTunisiaWidget.dart';
import 'package:untitled5/untitledapp/generatededitprofilewidget/generated/GeneratedChangeFullNameNameSurnameWidget.dart';
import 'package:untitled5/untitledapp/generatededitprofilewidget/generated/GeneratedVectorWidget802.dart';
import 'package:untitled5/untitledapp/generatededitprofilewidget/generated/GeneratedRectangle11Widget2.dart';
import 'package:untitled5/untitledapp/generatededitprofilewidget/generated/GeneratedRectangle12Widget2.dart';
import 'package:untitled5/untitledapp/generatededitprofilewidget/generated/GeneratedAvatarBackgroundWidget15.dart';
import 'package:untitled5/untitledapp/generatededitprofilewidget/generated/GeneratedVector25Widget18.dart';
import 'package:untitled5/untitledapp/generatededitprofilewidget/generated/GeneratedEditProfileWidget1.dart';
import 'package:untitled5/untitledapp/generatededitprofilewidget/generated/GeneratedAvatarWidget15.dart';

import '../../theme/themee.dart';

/* Frame Edit Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEditProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 930,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none, fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle2Widget13(),
                            ),
                            Positioned(
                              left: 311.0,
                              top: -107.0,
                              right: null,
                              bottom: null,
                              width: 239.564697265625,
                              height: 251.9700164794922,
                              child: GeneratedVectorWidget802(),
                            ),
                            Positioned(
                              left: 23.0,
                              top: 164.0,
                              right: null,
                              bottom: null,
                              width: 381.0,
                              height: 79.0,
                              child: GeneratedRectangle8Widget12(),
                            ),

                            Positioned(
                              left: 24.0,
                              top: 50.0,
                              right: null,
                              bottom: null,
                              width: 42.0,
                              height:40,
                              child:IconButton(onPressed: (){}, icon: Icon(Icons.arrow_back,size: 30,color: Colors.grey,),),
                            ),
                            Positioned(
                              left: 136.0,
                              top: 57.0,
                              right: null,
                              bottom: null,
                              width: 159.0,
                              height: 27.0,
                              child: GeneratedEditProfileWidget1(),
                            ),
                            Positioned(
                              left: 134.546875,
                              top: 1032.8741455078125,
                              right: null,
                              bottom: null,
                              width: 239.564697265625,
                              height: 251.9700164794922,
                              child: GeneratedVectorWidget803(),
                            ),
                            Positioned(
                              left: 41.0,
                              top: 169.0,
                              right: null,
                              bottom: null,
                              width: 68.0,
                              height: 68.0,
                              child: GeneratedAvatarBackgroundWidget15(),
                            ),
                            Positioned(
                              left: 39.0,
                              top: 174.0,
                              right: null,
                              bottom: null,
                              width: 67.0,
                              height: 67.0,
                              child: GeneratedAvatarWidget15(),
                            ),

                            Positioned(
                              left: 122.0,
                              top: 195.0,
                              right: null,
                              bottom: null,
                              width: 133.0,
                              height: 19.0,
                              child: GeneratedUploadPhotoWidget(),
                            ),
                            Positioned(
                              left: 123.5,
                              top: 218.0,
                              right: null,
                              bottom: null,
                              width: 129.0,
                              height: 0.0,
                              child: GeneratedVector40Widget(),
                            ),
                            Positioned(
                              left: 346.0,
                              top: 190.0,
                              right: null,
                              bottom: null,
                              width: 34.0,
                              height: 34.0,
                              child: InkWell(onTap: (){}, child: GeneratedFileFolder_UploadWidget()),
                            ),
                            Column(
                              children: [
                                SizedBox(height: 260,),
                                Container(
                                  height: 70,
                                  width: 380,
                                  padding: EdgeInsets.only(left: 190),
                                  margin: EdgeInsets.only(left: 10),
                                  decoration: BoxDecoration(
                                    borderRadius: BorderRadius.circular(30),
                                    color: Colors.white,
                                  ),
                                  child: SizedBox(
                                    width: 100,height: 100,
                                    child:  TextField(
                                      decoration: InputDecoration(
                                        border: InputBorder.none,
                                        hintText: ' Name Surname',
                                        hintStyle: TextStyle(
                                          color: AppColors.eight,
                                          fontSize: 16,
                                          fontWeight: FontWeight.w200,
                                          fontFamily: 'Montserrat',
                                        ),
                                        contentPadding: const EdgeInsets.only(
                                          top: 17,
                                        ),
                                      ),
                                    ),
                                  ),
                                  ),
                                SizedBox(height: 10,),
                                Container(
                                  height: 70,
                                  width: 380,
                                  padding: EdgeInsets.only(top: 15,left: 15),
                                  margin: EdgeInsets.only(left: 10),
                                  decoration: BoxDecoration(
                                    borderRadius: BorderRadius.circular(30),
                                    color: Colors.white,
                                  ),
                                  child: SizedBox(
                                    width: 100,height: 100,
                                    child:  TextField(
                                      decoration: InputDecoration(
                                        border: InputBorder.none,
                                        hintText: 'Username@gmail.com',
                                        hintStyle: TextStyle(
                                          color: AppColors.eight,
                                          fontSize: 16,
                                          fontWeight: FontWeight.w200,
                                          fontFamily: 'Montserrat',
                                        ),
                                        contentPadding: const EdgeInsets.only(
                                          top: 17,
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                                SizedBox(height: 10,),
                                Container(
                                  height: 70,
                                  width: 380,
                                  padding: EdgeInsets.only(top: 15,left: 15),
                                  margin: EdgeInsets.only(left: 10),
                                  decoration: BoxDecoration(
                                    borderRadius: BorderRadius.circular(30),
                                    color: Colors.white,
                                  ),
                                  child: SizedBox(
                                    width: 100,height: 100,
                                    child:  TextField(
                                      decoration: InputDecoration(
                                        border: InputBorder.none,
                                        hintText: '+216 99 999 999',
                                        hintStyle: TextStyle(
                                          color: AppColors.eight,
                                          fontSize: 16,
                                          fontWeight: FontWeight.w200,
                                          fontFamily: 'Montserrat',
                                        ),
                                        contentPadding: const EdgeInsets.only(
                                          top: 17,
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                                SizedBox(height: 10,),
                                Container(
                                  height: 70,
                                  width: 380,
                                  padding: EdgeInsets.only(top: 15,left: 15),
                                  margin: EdgeInsets.only(left: 10),
                                  decoration: BoxDecoration(
                                    borderRadius: BorderRadius.circular(30),
                                    color: Colors.white,
                                  ),
                                  child: SizedBox(
                                    width: 100,height: 100,
                                    child:  TextField(
                                      decoration: InputDecoration(
                                        border: InputBorder.none,
                                        hintText: 'Tunis, Tunisia',
                                        hintStyle: TextStyle(
                                          color: AppColors.eight,
                                          fontSize: 16,
                                          fontWeight: FontWeight.w200,
                                          fontFamily: 'Montserrat',
                                        ),
                                        contentPadding: const EdgeInsets.only(
                                          top: 17,
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                                SizedBox(height: 130,),
                                Container(
                                  width: 350,
                                  height: 40,
                                  child: RaisedButton(onPressed: (){},
                                    color: AppColors.third,
                                    shape: RoundedRectangleBorder(
                                        borderRadius: BorderRadius.circular(30)),
                                    child:
                                    Text('Apply',style: TextStyle(
                                      fontSize: 18,
                                      fontWeight: FontWeight.w700,
                                      fontFamily: 'Montserrat',
                                      color: Colors.white,
                                    ),),),
                                ),
                              ],
                            ),
                            Positioned(
                                top: 285,
                                left: 40,
                                child: Text('Change Full Name :', style: TextStyle(
                                  fontSize: 16,
                                  fontWeight: FontWeight.w200,
                                  fontFamily: 'Montserrat',
                                  color: Colors.grey,
                            ),)),
                            Positioned(
                                top: 350,
                                left: 40,
                                child: Text('Change Email Address :', style: TextStyle(
                                  fontSize: 16,
                                  fontWeight: FontWeight.w200,
                                  fontFamily: 'Montserrat',
                                  color: Colors.grey,
                                ),)),
                            Positioned(
                                top: 430,
                                left: 40,
                                child: Text('Change Phone Number:', style: TextStyle(
                                  fontSize: 16,
                                  fontWeight: FontWeight.w200,
                                  fontFamily: 'Montserrat',
                                  color: Colors.grey,
                                ),)),
                            Positioned(
                                top: 510,
                                left: 40,
                                child: Text('Change Delivery Addres:', style: TextStyle(
                                  fontSize: 16,
                                  fontWeight: FontWeight.w200,
                                  fontFamily: 'Montserrat',
                                  color: Colors.grey,
                                ),)),
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
