import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget1/generated/GeneratedRectangle15Widget2.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget1/generated/GeneratedUpcomingWidget2.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget1/generated/GeneratedItAppearsthatyourorderslistisemptyWidget.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget1/generated/GeneratedWavy_Bus26_Single01Converted1Widget.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget1/generated/GeneratedRectangle2Widget9.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget1/generated/GeneratedVector25Widget14.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget1/generated/GeneratedRectangle16Widget2.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget1/generated/GeneratedHistoryWidget2.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget1/generated/GeneratedMyOrdersWidget3.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget1/generated/GeneratedVectorWidget791.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget1/generated/GeneratedVectorWidget792.dart';

/* Frame Orders History
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOrdersHistoryWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 930.8441619873047,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none, fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle2Widget9(),
                            ),
                            Positioned(
                              left: 311.0,
                              top: -107.0,
                              right: null,
                              bottom: null,
                              width: 239.564697265625,
                              height: 251.9700164794922,
                              child: GeneratedVectorWidget791(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 70.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 0.0,
                              child: GeneratedVector25Widget14(),
                            ),
                            Positioned(
                              left: 150.0,
                              top: 58.0,
                              right: null,
                              bottom: null,
                              width: 130.0,
                              height: 25.0,
                              child: GeneratedMyOrdersWidget3(),
                            ),
                            Positioned(
                              left: 134.546875,
                              top: 1058.8741455078125,
                              right: null,
                              bottom: null,
                              width: 239.564697265625,
                              height: 251.9700164794922,
                              child: GeneratedVectorWidget792(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 156.0,
                              right: null,
                              bottom: null,
                              width: 366.0,
                              height: 62.0,
                              child: GeneratedRectangle15Widget2(),
                            ),
                            Positioned(
                              left: 215.0,
                              top: 161.0,
                              right: null,
                              bottom: null,
                              width: 176.0,
                              height: 53.0,
                              child: InkWell(onTap : () {} , child: GeneratedRectangle16Widget2()),
                            ),
                            Positioned(
                              left: 58.0,
                              top: 176.0,
                              right: null,
                              bottom: null,
                              width: 138.0,
                              height: 28.0,
                              child: Container(width : 100, height : 50 , child: InkWell(onTap : () {} ,child: GeneratedUpcomingWidget2())),
                            ),
                            Positioned(
                              left: 261.0,
                              top: 176.0,
                              right: null,
                              bottom: null,
                              width: 99.0,
                              height: 28.0,
                              child: InkWell(onTap : () {} ,child: GeneratedHistoryWidget2()),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 390.0,
                              right: null,
                              bottom: null,
                              width: 365.0,
                              height: 373.0,
                              child:
                                  GeneratedWavy_Bus26_Single01Converted1Widget(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 264.0,
                              right: null,
                              bottom: null,
                              width: 371.0,
                              height: 74.0,
                              child:
                                  GeneratedItAppearsthatyourorderslistisemptyWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
