import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedRectangle29Widget1.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedEllipse25Widget.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedOrderCanceledWidget.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedOrderdeliveredWidget1.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedRectangle2Widget8.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/Generated2May1030Widget.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedRectangle22Widget6.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedReOrderWidget1.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedEllipse24Widget1.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedUpcomingWidget1.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedAjHrkqeGvr6NF3eZSs3f1Widget1.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedVector25Widget13.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedVector30Widget3.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedBaguetteBaguetteWidget11.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedRateWidget2.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedRectangle17Widget6.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedRectangle16Widget1.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedVectorWidget790.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedRectangle28Widget1.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedVectorWidget789.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedMyOrdersWidget2.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/Generated3itemsWidget2.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedRectangle24Widget7.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/Generated30DtWidget1.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/Generated20June1030Widget1.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedRectangle15Widget1.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedAjHrkqeGvr6NF3eZSs3f2Widget1.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedRectangle19Widget5.dart';
import 'package:untitled5/helpers/transform/transform.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedRectangle25Widget8.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedReOrderWidget2.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedRateWidget1.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedRectangle9Widget5.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedBaguetteBaguetteWidget10.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/Generated5itemsWidget.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/Generated75DtWidget.dart';
import 'package:untitled5/untitledapp/generatedordershistorywidget/generated/GeneratedHistoryWidget1.dart';

import '../../theme/themee.dart';

/* Frame Orders History
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOrdersHistoryWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 930.8441619873047,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none, fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle2Widget8(),
                            ),
                            Positioned(
                              left: 311.0,
                              top: -107.0,
                              right: null,
                              bottom: null,
                              width: 239.564697265625,
                              height: 251.9700164794922,
                              child: GeneratedVectorWidget789(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 70.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 0.0,
                              child: GeneratedVector25Widget13(),
                            ),
                            Positioned(
                              left: 150.0,
                              top: 58.0,
                              right: null,
                              bottom: null,
                              width: 130.0,
                              height: 25.0,
                              child: GeneratedMyOrdersWidget2(),
                            ),
                            Positioned(
                              left: 134.546875,
                              top: 1058.8741455078125,
                              right: null,
                              bottom: null,
                              width: 239.564697265625,
                              height: 251.9700164794922,
                              child: GeneratedVectorWidget790(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 156.0,
                              right: null,
                              bottom: null,
                              width: 366.0,
                              height: 62.0,
                              child: GeneratedRectangle15Widget1(),
                            ),
                            Positioned(
                              left: 215.0,
                              top: 161.0,
                              right: null,
                              bottom: null,
                              width: 176.0,
                              height: 53.0,
                              child: InkWell( onTap : (){}, child: GeneratedRectangle16Widget1()),
                            ),
                            Column(
                              children: [
                                SizedBox(height: 250,),
                                Container(
                                  width: 350,
                                  height: 230,
                                  decoration: BoxDecoration(
                                    borderRadius: BorderRadius.circular(40),
                                    color: Colors.white,
                                  ),
                                  child:
                                  Column(
                                    children: [
                                      SizedBox(height: 20,),
                                      Row(
                                        children: [
                                          SizedBox(width: 10,),
                                          ClipRRect(
                                            borderRadius: BorderRadius.circular(15.0),
                                            child: Image.asset(
                                              "assets/images/730fb5eca818b765788f68b314c27079ca14d511.png",
                                              height: 70,
                                              width: 70,
                                              fit: BoxFit.fitWidth,
                                            ),
                                          ),
                                          SizedBox(width: 8,),
                                          Column(
                                            crossAxisAlignment: CrossAxisAlignment.start,
                                            children: [
                                              Row(children : [Text('20, June, 10:30',
                                                style: TextStyle(
                                                  fontSize: 12,
                                                  fontWeight: FontWeight.w400,
                                                  fontFamily: 'Montserrat',
                                                  color: Colors.grey,
                                                ),),
                                                SizedBox(width: 30,),
                                                Text('3items',style: TextStyle(
                                                  fontSize: 12,
                                                  fontWeight: FontWeight.w400,
                                                  fontFamily: 'Montserrat',
                                                  color: Colors.grey,
                                                ),),
                                                SizedBox(width: 30,),
                                                Text('30DT',style: TextStyle(
                                                  fontSize: 14,
                                                  fontWeight: FontWeight.w400,
                                                  fontFamily: 'Montserrat',
                                                  color: AppColors.fifth,
                                                ),)
                                              ]),
                                              SizedBox(height: 4,),
                                              Text('Baguette & Baguette',style: TextStyle(
                                                fontSize: 15,
                                                fontWeight: FontWeight.w700,
                                                fontFamily: 'Montserrat',
                                              ),),
                                            ],
                                          ),
                                        ],
                                      ),
                                      SizedBox(height: 10,),
                                      Row(children: [
                                        SizedBox(width: 20,),
                                        Icon(Icons.circle,size: 20,color: Colors.lightGreen),
                                        SizedBox(width: 6,),
                                        Text('Order Delivered',style: TextStyle(
                                          fontSize: 12,
                                          fontWeight: FontWeight.w700,
                                          fontFamily: 'Montserrat',
                                          color: Colors.lightGreen,
                                        ),),
                                      ],),
                                      SizedBox(height: 30,),
                                      Row(children: [
                                        SizedBox(width: 50,),
                                        Container(
                                          width : 110,
                                          child: RaisedButton(onPressed: (){},child: Text('Rate',style: TextStyle(
                                            fontSize: 13,
                                            fontWeight: FontWeight.w500,
                                            fontFamily: 'Montserrat',
                                          ),),
                                            color: Colors.white,
                                            shape: RoundedRectangleBorder(
                                                borderRadius: BorderRadius.circular(30)),
                                          ),
                                        ),
                                        SizedBox(width: 20,),
                                        Container(
                                          width: 110,
                                          child: RaisedButton(onPressed: (){},child: Text('Re-Order',style: TextStyle(
                                            color: Colors.white,
                                            fontSize: 13,
                                            fontWeight: FontWeight.w500,
                                            fontFamily: 'Montserrat',
                                          ),),
                                            color: AppColors.fifth,
                                            shape: RoundedRectangleBorder(
                                                borderRadius: BorderRadius.circular(30)),),
                                        ),
                                      ],),
                                    ],
                                  ),
                                ),
                                SizedBox(height: 50,),
                                Container(
                                  width: 350,
                                  height: 230,
                                  decoration: BoxDecoration(
                                    borderRadius: BorderRadius.circular(40),
                                    color: Colors.white,
                                  ),
                                  child:
                                  Column(
                                    children: [
                                      SizedBox(height: 20,),
                                      Row(
                                        children: [
                                          SizedBox(width: 10,),
                                          ClipRRect(
                                            borderRadius: BorderRadius.circular(15.0),
                                            child: Image.asset(
                                              "assets/images/730fb5eca818b765788f68b314c27079ca14d511.png",
                                              height: 70,
                                              width: 70,
                                              fit: BoxFit.fitWidth,
                                            ),
                                          ),
                                          SizedBox(width: 8,),
                                          Column(
                                            crossAxisAlignment: CrossAxisAlignment.start,
                                            children: [
                                              Row(children : [Text('2, May, 10:30',
                                                style: TextStyle(
                                                  fontSize: 12,
                                                  fontWeight: FontWeight.w400,
                                                  fontFamily: 'Montserrat',
                                                  color: Colors.grey,
                                                ),),
                                                SizedBox(width: 30,),
                                                Text('5items',style: TextStyle(
                                                  fontSize: 12,
                                                  fontWeight: FontWeight.w400,
                                                  fontFamily: 'Montserrat',
                                                  color: Colors.grey,
                                                ),),
                                                SizedBox(width: 30,),
                                                Text('75DT',style: TextStyle(
                                                  fontSize: 14,
                                                  fontWeight: FontWeight.w400,
                                                  fontFamily: 'Montserrat',
                                                  color: AppColors.fifth,
                                                ),)
                                              ]),
                                              SizedBox(height: 4,),
                                              Text('Baguette & Baguette',style: TextStyle(
                                                fontSize: 15,
                                                fontWeight: FontWeight.w700,
                                                fontFamily: 'Montserrat',
                                              ),),
                                            ],
                                          ),
                                        ],
                                      ),
                                      SizedBox(height: 10,),
                                      Row(children: [
                                        SizedBox(width: 20,),
                                        Icon(Icons.circle,size: 20,color: Colors.red),
                                        SizedBox(width: 6,),
                                        Text('Order Canceled',style: TextStyle(
                                          fontSize: 12,
                                          fontWeight: FontWeight.w700,
                                          fontFamily: 'Montserrat',
                                          color: Colors.red,
                                        ),),
                                      ],),
                                      SizedBox(height: 30,),
                                      Row(children: [
                                        SizedBox(width: 50,),
                                        Container(
                                          width : 110,
                                          child: RaisedButton(onPressed: (){},child: Text('Rate',style: TextStyle(
                                            fontSize: 13,
                                            fontWeight: FontWeight.w500,
                                            fontFamily: 'Montserrat',
                                          ),),
                                            color: Colors.white,
                                            shape: RoundedRectangleBorder(
                                                borderRadius: BorderRadius.circular(30)),
                                          ),
                                        ),
                                        SizedBox(width: 20,),
                                        Container(
                                          width: 110,
                                          child: RaisedButton(onPressed: (){},child: Text('Re-Order',style: TextStyle(
                                            color: Colors.white,
                                            fontSize: 13,
                                            fontWeight: FontWeight.w500,
                                            fontFamily: 'Montserrat',
                                          ),),
                                            color: AppColors.fifth,
                                            shape: RoundedRectangleBorder(
                                                borderRadius: BorderRadius.circular(30)),),
                                        ),
                                      ],),
                                    ],
                                  ),
                                ),
                              ],
                            ),
                            Positioned(
                              left: 58.0,
                              top: 176.0,
                              right: null,
                              bottom: null,
                              width: 138.0,
                              height: 28.0,
                              child: Container(width : 100, height : 50, child: InkWell(onTap : () {} , child: GeneratedUpcomingWidget1())),
                            ),
                            Positioned(
                              left: 261.0,
                              top: 176.0,
                              right: null,
                              bottom: null,
                              width: 99.0,
                              height: 28.0,
                              child: InkWell(onTap : () {} , child: GeneratedHistoryWidget1()),
                            ),
                            Positioned(
                              left: 195.0,
                              top: 804.0,
                              right: null,
                              bottom: null,
                              width: 38.0,
                              height: 0.0,
                              child: InkWell(onTap : () {} , child: GeneratedVector30Widget3()),
                            ),
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
